{
  "post_stream": {
    "posts": [
      {
        "id": 5988,
        "name": "Leo Hu",
        "username": "lehu",
        "avatar_template": "/user_avatar/forums.foundationdb.org/lehu/{size}/995_2.png",
        "created_at": "2020-01-22T20:43:37.430Z",
        "cooked": "<p>We are deploying FDB 6.2 on Ubuntu 16.04. When restarting the service, I got the following error:</p>\n<p>root@nontls62-storage-02-7d9d989ffd-d9cpv:~# service foundationdb restart<br>\n/etc/init.d/foundationdb: line 94: log_daemon_msg: command not found<br>\ncommand terminated with exit code 137<br>\n506 k8s $</p>\n<p>In addition to the error, the restart also exited the Shell. In the above the first line is my Kubernetes pod\u2019s Shell, and the fourth line is my local Mac Shell.</p>\n<p>How can we overcome this? Thanks.</p>\n<p>Leo</p>",
        "post_number": 1,
        "post_type": 1,
        "posts_count": 6,
        "updated_at": "2020-01-22T20:43:37.430Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 782,
        "reads": 19,
        "readers_count": 18,
        "score": 3913.8,
        "yours": false,
        "topic_id": 1895,
        "topic_slug": "log-daemon-msg-error-when-restarting-service-on-ubuntu",
        "display_username": "Leo Hu",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 643,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/log-daemon-msg-error-when-restarting-service-on-ubuntu/1895/1",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null,
        "can_vote": false
      },
      {
        "id": 5995,
        "name": "Alex Miller",
        "username": "alexmiller",
        "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
        "created_at": "2020-01-23T00:00:15.030Z",
        "cooked": "<p><code>log_daemon_msg</code> comes from <code>/lib/lsb/init-functions</code>, and <code>/etc/init.d/founationdb</code> has commented out:</p>\n<pre><code class=\"lang-auto\">\n# Define LSB log_* functions.\n# Depend on lsb-base (&gt;= 3.2-14) to ensure that this file is present\n# and status_of_proc is working.\n# Installation failed on Ubuntu 16.04 or later due to init-functions calling systemctl which tries to find foundationdb.service \n# under /lib/systemd/system. Hence comment out it for now.\n# . /lib/lsb/init-functions\n</code></pre>\n<p>So you can try uncommenting that include, and see what happens.  In general, our Ubuntu packages have been kind of stranded by the init system change, as trying to keep one package compatible across both has been\u2026 rather challenging.</p>\n<p>The definitions of the log_* functions aren\u2019t that complicated either, and other projects have just copied them into the init script, which we could also do.  If you copy the definition of <code>log_daemon_msg</code> and <code>log_end_msg</code> from wherever they\u2019re defined in /lib/init/ , does the script then run and work for you?</p>",
        "post_number": 2,
        "post_type": 1,
        "posts_count": 6,
        "updated_at": "2020-01-23T00:00:15.030Z",
        "reply_count": 1,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 3,
        "reads": 18,
        "readers_count": 17,
        "score": 23.6,
        "yours": false,
        "topic_id": 1895,
        "topic_slug": "log-daemon-msg-error-when-restarting-service-on-ubuntu",
        "display_username": "Alex Miller",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 13,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/log-daemon-msg-error-when-restarting-service-on-ubuntu/1895/2",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6014,
        "name": "Leo Hu",
        "username": "lehu",
        "avatar_template": "/user_avatar/forums.foundationdb.org/lehu/{size}/995_2.png",
        "created_at": "2020-01-23T21:30:07.475Z",
        "cooked": "<p>Hi Alex,</p>\n<p>Thanks for the tips. I tried them and also with a new OS version. Here is what I\u2019ve found out.</p>\n<ul>\n<li>\n<p>With Ubuntu 16.04, uncommenting the line of /lib/lsb/init-functions would get rid of the log_daemon_msg errors, but it would still exit the shell.</p>\n</li>\n<li>\n<p>Copying specific functions to /etc/init.d/foundationdb has the same behavior.</p>\n</li>\n<li>\n<p>I built another Docker image with \u201cUbuntu 18.04.3 LTS\u201d, and uncommented the line. This would get rid of the error msgs AND stay in the shell! That\u2019s nice.</p>\n</li>\n</ul>\n<p>My question now: is Ubuntu 18.04 a good version for FDB 6.2?</p>\n<p>Leo</p>",
        "post_number": 3,
        "post_type": 1,
        "posts_count": 6,
        "updated_at": "2020-01-23T21:30:07.475Z",
        "reply_count": 1,
        "reply_to_post_number": 2,
        "quote_count": 0,
        "incoming_link_count": 4,
        "reads": 15,
        "readers_count": 14,
        "score": 28.0,
        "yours": false,
        "topic_id": 1895,
        "topic_slug": "log-daemon-msg-error-when-restarting-service-on-ubuntu",
        "display_username": "Leo Hu",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 13,
          "username": "alexmiller",
          "name": "Alex Miller",
          "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 643,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/log-daemon-msg-error-when-restarting-service-on-ubuntu/1895/3",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6018,
        "name": "Alex Miller",
        "username": "alexmiller",
        "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
        "created_at": "2020-01-24T00:06:56.189Z",
        "cooked": "<p>Then there\u2019s something unrelated that\u2019s causing the shell to exit.  (Is fdbmonitor running as PID 1?)</p>\n<p>But if Ubuntu 18.04 works for you, then it should be fine to use.</p>",
        "post_number": 4,
        "post_type": 1,
        "posts_count": 6,
        "updated_at": "2020-01-24T00:06:56.189Z",
        "reply_count": 1,
        "reply_to_post_number": 3,
        "quote_count": 0,
        "incoming_link_count": 3,
        "reads": 15,
        "readers_count": 14,
        "score": 23.0,
        "yours": false,
        "topic_id": 1895,
        "topic_slug": "log-daemon-msg-error-when-restarting-service-on-ubuntu",
        "display_username": "Alex Miller",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 643,
          "username": "lehu",
          "name": "Leo Hu",
          "avatar_template": "/user_avatar/forums.foundationdb.org/lehu/{size}/995_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 13,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/log-daemon-msg-error-when-restarting-service-on-ubuntu/1895/4",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6019,
        "name": "Leo Hu",
        "username": "lehu",
        "avatar_template": "/user_avatar/forums.foundationdb.org/lehu/{size}/995_2.png",
        "created_at": "2020-01-24T00:25:27.558Z",
        "cooked": "<p>No, fdbmonitor is not running as PID 1. I see it as PID 6.</p>\n<p>We use Docker and have a container init/startup program before fdbmonitor. That program named Tini has PID 1.</p>\n<p>Thank you.<br>\nLeo</p>",
        "post_number": 5,
        "post_type": 1,
        "posts_count": 6,
        "updated_at": "2020-01-24T00:25:27.558Z",
        "reply_count": 0,
        "reply_to_post_number": 4,
        "quote_count": 0,
        "incoming_link_count": 10,
        "reads": 13,
        "readers_count": 12,
        "score": 52.6,
        "yours": false,
        "topic_id": 1895,
        "topic_slug": "log-daemon-msg-error-when-restarting-service-on-ubuntu",
        "display_username": "Leo Hu",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 13,
          "username": "alexmiller",
          "name": "Alex Miller",
          "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 643,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/log-daemon-msg-error-when-restarting-service-on-ubuntu/1895/5",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 10180,
        "name": "Damien Leroux",
        "username": "damienleroux",
        "avatar_template": "/user_avatar/forums.foundationdb.org/damienleroux/{size}/1212_2.png",
        "created_at": "2021-10-28T14:54:34.841Z",
        "cooked": "<p>I met the same problem running <code>service foundationdb restart</code> on a local dockerized container running on Ubuntu 20.04:</p>\n<pre><code class=\"lang-auto\">root@b5e2288f16ba:/# service foundationdb restart\n/etc/init.d/foundationdb: line 94: log_daemon_msg: command not found\n/etc/init.d/foundationdb: line 100: log_end_msg: command not found\n</code></pre>\n<p>I resolved the issue running instead: <code>service foundationdb stop &amp;&amp; sudo service foundationdb start</code>. It seems that &amp; two-steps process is working.</p>",
        "post_number": 6,
        "post_type": 1,
        "posts_count": 6,
        "updated_at": "2021-10-28T14:56:46.972Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 2,
        "reads": 8,
        "readers_count": 7,
        "score": 11.6,
        "yours": false,
        "topic_id": 1895,
        "topic_slug": "log-daemon-msg-error-when-restarting-service-on-ubuntu",
        "display_username": "Damien Leroux",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 1020,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/log-daemon-msg-error-when-restarting-service-on-ubuntu/1895/6",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      }
    ],
    "stream": [
      5988,
      5995,
      6014,
      6018,
      6019,
      10180
    ]
  },
  "timeline_lookup": [
    [
      1,
      2099
    ],
    [
      3,
      2098
    ],
    [
      6,
      1454
    ]
  ],
  "suggested_topics": [],
  "tags": [],
  "tags_descriptions": {},
  "fancy_title": "Log_daemon_msg error when restarting service on Ubuntu",
  "id": 1895,
  "title": "Log_daemon_msg error when restarting service on Ubuntu",
  "posts_count": 6,
  "created_at": "2020-01-22T20:43:37.370Z",
  "views": 2156,
  "reply_count": 3,
  "like_count": 0,
  "last_posted_at": "2021-10-28T14:54:34.841Z",
  "visible": true,
  "closed": false,
  "archived": false,
  "has_summary": false,
  "archetype": "regular",
  "slug": "log-daemon-msg-error-when-restarting-service-on-ubuntu",
  "category_id": 7,
  "word_count": 490,
  "deleted_at": null,
  "user_id": 643,
  "featured_link": null,
  "pinned_globally": false,
  "pinned_at": null,
  "pinned_until": null,
  "image_url": null,
  "slow_mode_seconds": 0,
  "draft": null,
  "draft_key": "topic_1895",
  "draft_sequence": null,
  "unpinned": null,
  "pinned": false,
  "current_post_number": 1,
  "highest_post_number": 6,
  "deleted_by": null,
  "actions_summary": [
    {
      "id": 4,
      "count": 0,
      "hidden": false,
      "can_act": false
    },
    {
      "id": 8,
      "count": 0,
      "hidden": false,
      "can_act": false
    },
    {
      "id": 10,
      "count": 0,
      "hidden": false,
      "can_act": false
    },
    {
      "id": 7,
      "count": 0,
      "hidden": false,
      "can_act": false
    }
  ],
  "chunk_size": 20,
  "bookmarked": false,
  "topic_timer": null,
  "message_bus_last_id": 0,
  "participant_count": 3,
  "show_read_indicator": false,
  "thumbnails": null,
  "slow_mode_enabled_until": null,
  "tags_disable_ads": false,
  "related_topics": [
    {
      "fancy_title": "Did something change in fdbmonitor in 5.2.5?",
      "id": 537,
      "title": "Did something change in fdbmonitor in 5.2.5?",
      "slug": "did-something-change-in-fdbmonitor-in-5-2-5",
      "posts_count": 3,
      "reply_count": 1,
      "highest_post_number": 3,
      "image_url": null,
      "created_at": "2018-07-03T05:05:03.793Z",
      "last_posted_at": "2018-07-04T09:32:34.750Z",
      "bumped": true,
      "bumped_at": "2018-07-04T09:32:34.750Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 1,
      "views": 954,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": null,
          "description": "Original Poster",
          "user": {
            "id": 38,
            "username": "panghy",
            "name": "Clement Pang",
            "avatar_template": "/user_avatar/forums.foundationdb.org/panghy/{size}/19_2.png",
            "trust_level": 2
          }
        },
        {
          "extras": "latest",
          "description": "Most Recent Poster",
          "user": {
            "id": 53,
            "username": "KrzysFR",
            "name": "Christophe Chevalier",
            "avatar_template": "/user_avatar/forums.foundationdb.org/krzysfr/{size}/43_2.png",
            "trust_level": 2
          }
        }
      ]
    },
    {
      "fancy_title": "Starting/Stoping the Server",
      "id": 1407,
      "title": "Starting/Stoping the Server",
      "slug": "starting-stoping-the-server",
      "posts_count": 8,
      "reply_count": 6,
      "highest_post_number": 8,
      "image_url": null,
      "created_at": "2019-05-29T22:07:38.479Z",
      "last_posted_at": "2019-05-31T22:06:15.164Z",
      "bumped": true,
      "bumped_at": "2019-05-31T22:06:15.164Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 0,
      "views": 2251,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": null,
          "description": "Original Poster",
          "user": {
            "id": 594,
            "username": "zhuyi29",
            "name": "Zoe",
            "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/z/edb3f5/{size}.png",
            "trust_level": 1
          }
        },
        {
          "extras": "latest",
          "description": "Most Recent Poster",
          "user": {
            "id": 12,
            "username": "ajbeamon",
            "name": "A.J. Beamon",
            "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png",
            "admin": true,
            "trust_level": 4
          }
        }
      ]
    },
    {
      "fancy_title": "Simple Dockerfile",
      "id": 280,
      "title": "Simple Dockerfile",
      "slug": "simple-dockerfile",
      "posts_count": 17,
      "reply_count": 10,
      "highest_post_number": 17,
      "image_url": null,
      "created_at": "2018-04-26T09:05:55.151Z",
      "last_posted_at": "2018-10-16T20:26:01.085Z",
      "bumped": true,
      "bumped_at": "2018-10-16T20:26:01.085Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 9,
      "views": 8840,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": null,
          "description": "Original Poster",
          "user": {
            "id": 187,
            "username": "hiroshi",
            "name": "",
            "avatar_template": "/user_avatar/forums.foundationdb.org/hiroshi/{size}/147_2.png",
            "trust_level": 1
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 13,
            "username": "alexmiller",
            "name": "Alex Miller",
            "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
            "trust_level": 4
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 247,
            "username": "Chr1st0ph",
            "name": "Chr1st0ph",
            "avatar_template": "/user_avatar/forums.foundationdb.org/chr1st0ph/{size}/353_2.png",
            "trust_level": 2
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 256,
            "username": "bjrnio",
            "name": "Ricard Bejarano",
            "avatar_template": "/user_avatar/forums.foundationdb.org/bjrnio/{size}/235_2.png",
            "trust_level": 0
          }
        },
        {
          "extras": "latest",
          "description": "Most Recent Poster",
          "user": {
            "id": 392,
            "username": "pavibhai",
            "name": "Pavan",
            "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/p/e56c9b/{size}.png",
            "trust_level": 0
          }
        }
      ]
    },
    {
      "fancy_title": "How to connect to FoundationDB with MongoDB CLI?",
      "id": 977,
      "title": "How to connect to FoundationDB with MongoDB CLI?",
      "slug": "how-to-connect-to-foundationdb-with-mongodb-cli",
      "posts_count": 4,
      "reply_count": 2,
      "highest_post_number": 4,
      "image_url": null,
      "created_at": "2018-12-28T15:06:54.534Z",
      "last_posted_at": "2019-01-02T23:14:14.408Z",
      "bumped": true,
      "bumped_at": "2019-01-02T23:14:14.408Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 0,
      "views": 1621,
      "category_id": 11,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": null,
          "description": "Original Poster",
          "user": {
            "id": 465,
            "username": "xet7",
            "name": "xet7",
            "avatar_template": "/user_avatar/forums.foundationdb.org/xet7/{size}/460_2.png",
            "trust_level": 0
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 13,
            "username": "alexmiller",
            "name": "Alex Miller",
            "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
            "trust_level": 4
          }
        },
        {
          "extras": "latest",
          "description": "Most Recent Poster",
          "user": {
            "id": 9,
            "username": "mbhaskar",
            "name": "Bhaskar Muppana",
            "avatar_template": "/user_avatar/forums.foundationdb.org/mbhaskar/{size}/277_2.png",
            "trust_level": 4
          }
        }
      ]
    },
    {
      "fancy_title": "Foundationdb seems keep reinitialising itself after client hang",
      "id": 1437,
      "title": "Foundationdb seems keep reinitialising itself after client hang",
      "slug": "foundationdb-seems-keep-reinitialising-itself-after-client-hang",
      "posts_count": 6,
      "reply_count": 2,
      "highest_post_number": 6,
      "image_url": null,
      "created_at": "2019-06-10T10:10:13.209Z",
      "last_posted_at": "2019-06-26T18:08:03.629Z",
      "bumped": true,
      "bumped_at": "2019-06-26T18:08:03.629Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 1,
      "views": 1222,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": null,
          "description": "Original Poster",
          "user": {
            "id": 602,
            "username": "ppggff",
            "name": "ppggff",
            "avatar_template": "/user_avatar/forums.foundationdb.org/ppggff/{size}/855_2.png",
            "trust_level": 1
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 166,
            "username": "gaurav",
            "name": "gaurav",
            "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/g/b487fb/{size}.png",
            "trust_level": 3
          }
        },
        {
          "extras": "latest",
          "description": "Most Recent Poster",
          "user": {
            "id": 13,
            "username": "alexmiller",
            "name": "Alex Miller",
            "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
            "trust_level": 4
          }
        }
      ]
    }
  ],
  "summarizable": false,
  "can_vote": false,
  "vote_count": 0,
  "user_voted": false,
  "discourse_zendesk_plugin_zendesk_id": null,
  "discourse_zendesk_plugin_zendesk_url": "https://your-url.zendesk.com/agent/tickets/",
  "details": {
    "can_edit": false,
    "notification_level": 1,
    "participants": [
      {
        "id": 643,
        "username": "lehu",
        "name": "Leo Hu",
        "avatar_template": "/user_avatar/forums.foundationdb.org/lehu/{size}/995_2.png",
        "post_count": 3,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "trust_level": 1
      },
      {
        "id": 13,
        "username": "alexmiller",
        "name": "Alex Miller",
        "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
        "post_count": 2,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "trust_level": 4
      },
      {
        "id": 1020,
        "username": "damienleroux",
        "name": "Damien Leroux",
        "avatar_template": "/user_avatar/forums.foundationdb.org/damienleroux/{size}/1212_2.png",
        "post_count": 1,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "trust_level": 1
      }
    ],
    "created_by": {
      "id": 643,
      "username": "lehu",
      "name": "Leo Hu",
      "avatar_template": "/user_avatar/forums.foundationdb.org/lehu/{size}/995_2.png"
    },
    "last_poster": {
      "id": 1020,
      "username": "damienleroux",
      "name": "Damien Leroux",
      "avatar_template": "/user_avatar/forums.foundationdb.org/damienleroux/{size}/1212_2.png"
    }
  },
  "bookmarks": []
}