{
  "post_stream": {
    "posts": [
      {
        "id": 6010,
        "name": "Leo Hu",
        "username": "lehu",
        "avatar_template": "/user_avatar/forums.foundationdb.org/lehu/{size}/995_2.png",
        "created_at": "2020-01-23T17:31:13.451Z",
        "cooked": "<p>I am able to bring up non-TLS clusters with FDB v6.2, but have difficulties to create a TLS v6.2 cluster.</p>\n<p>By following instructions in <a href=\"https://apple.github.io/foundationdb/tls.html\" rel=\"nofollow noopener\">https://apple.github.io/foundationdb/tls.html</a>, we tried two approaches:</p>\n<ul>\n<li>Setting Up FoundationDB to use TLS</li>\n<li>Converting an existing cluster to use TLS (since v6.1).</li>\n</ul>\n<p>Neither succeeded. Here are some details.</p>\n<p>Our env:<br>\nFDB v6.2.10<br>\nUbuntu 18.04<br>\nUsing Docker containers with Kubernetes.<br>\nEach Storage K8s pod has two processes at 4500 and 4501.</p>\n<ol>\n<li>\u201cSetting Up FoundationDB to use TLS\u201d approach</li>\n</ol>\n<p>When using \u201c-t\u201d flag on make_public.py (at the Docker container startup), we see the coordinator in fdb.cluster file has \u201c:tls\u201d suffix, e\u2026g,<br>\n4QzbRd0m:ItkkDDfp@10.104.193.12:4500:tls</p>\n<p>However, the processes on the container seem abnormal. There are 3 fdbmonitor processes, but only 1 fdbserver process (supposed to have 2 at 4500 and 4501), as follows:</p>\n<pre><code>root@tls62-storage-01-76cd5f5b99-trqhh:~# ps aux\nUSER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND\nroot         6  0.0  0.0  12644  1052 ?        S    07:26   0:00 /usr/lib/foundationdb/fdbmonitor\nroot        20  0.0  0.0  21076  3016 ?        Ss   07:26   0:00 /usr/lib/foundationdb/fdbmonitor --conffile /etc/foundationdb/foundationdb.conf --lockfile /var/run/fdbmonitor.pid --daemonize\nfoundat+    34  0.1  0.0 331732 19420 ?        Sl   07:26   0:00 /usr/sbin/fdbserver --class storage --cluster_file /var/lib/foundationdb/fdb.cluster --datacenter_id dc1 --datadir /var/lib/foundat\nroot        40  0.0  0.0  34448 12200 ?        Sl   07:26   0:00 fdbcli --no-status --exec configure new single memory\nroot        47  0.0  0.0  21076   248 ?        S    07:30   0:00 /usr/lib/foundationdb/fdbmonitor --conffile /etc/foundationdb/foundationdb.conf --lockfile /var/run/fdbmonitor.pid --daemonize\n</code></pre>\n<p>Also there is a trace file under /var/log/foundation associated with 4501, but none for 4500.</p>\n<pre><code>root@tls62-storage-01-76cd5f5b99-trqhh:/var/log# ll foundationdb/\ntotal 1604\n-rw-r--r-- 1 foundationdb foundationdb     743 Jan 23 07:26 trace.10.104.193.12.22.1579764417.yVrDKA.0.1.xml\n-rw-r--r-- 1 foundationdb foundationdb 1457778 Jan 23 07:42 trace.10.104.193.12.4501.1579764417.KoUk1T.0.1.xml\n</code></pre>\n<p>The resulting db is unavailable.</p>\n<ol start=\"2\">\n<li>\u201cConverting an existing cluster to use TLS (since v6.1)\u201d approach<br>\nTaking out the \u201c-t\u201d flag of make_public.py, we created the whole cluster in non-TLS first, then convert it to TLS, following the instructions in the doc.</li>\n</ol>\n<p>Restarting fdbserver gave me this error:</p>\n<pre><code>root@tls62-storage-01-76cd5f5b99-c9w22:~# fdbserver -C /var/lib/foundationdb/fdb.cluster -p 10.104.193.12:4500 -p 10.104.193.12:4501:tls\n\n    Error initializing networking with public address 10.104.193.12:4500 and listen address 10.104.193.12:4500 (Local address in use)\n\n    Try `fdbserver --help' for more information.\n</code></pre>\n<p>Please help. Thank you.</p>\n<p>Leo</p>",
        "post_number": 1,
        "post_type": 1,
        "posts_count": 12,
        "updated_at": "2020-01-23T17:31:13.451Z",
        "reply_count": 1,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 239,
        "reads": 55,
        "readers_count": 54,
        "score": 1211.0,
        "yours": false,
        "topic_id": 1904,
        "topic_slug": "issues-with-v6-2-tls-cluster",
        "display_username": "Leo Hu",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "link_counts": [
          {
            "url": "https://apple.github.io/foundationdb/tls.html",
            "internal": false,
            "reflection": false,
            "title": "Transport Layer Security \u2014 FoundationDB 6.2",
            "clicks": 8
          }
        ],
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 643,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/issues-with-v6-2-tls-cluster/1904/1",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null,
        "can_vote": false
      },
      {
        "id": 6011,
        "name": "A.J. Beamon",
        "username": "ajbeamon",
        "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png",
        "created_at": "2020-01-23T17:37:52.174Z",
        "cooked": "<aside class=\"quote no-group\" data-username=\"lehu\" data-post=\"1\" data-topic=\"1904\">\n<div class=\"title\">\n<div class=\"quote-controls\"></div>\n<img loading=\"lazy\" alt=\"\" width=\"24\" height=\"24\" src=\"https://sea1.discourse-cdn.com/foundationdb/user_avatar/forums.foundationdb.org/lehu/48/995_2.png\" class=\"avatar\"> lehu:</div>\n<blockquote>\n<p>However, the processes on the container seem abnormal. There are 3 fdbmonitor processes, but only 1 fdbserver process (supposed to have 2 at 4500 and 4501), as follows:</p>\n</blockquote>\n</aside>\n<p><code>fdbmonitor</code> starts child processes by forking itself. In the cases where the child process fails and requires a backoff, you\u2019ll see these extra <code>fdbmonitor</code> processes before it execs the child executable again. Check the <code>fdbmonitor</code> logs (in syslog) for information about why the child processes are failing.</p>\n<aside class=\"quote no-group\" data-username=\"lehu\" data-post=\"1\" data-topic=\"1904\">\n<div class=\"title\">\n<div class=\"quote-controls\"></div>\n<img loading=\"lazy\" alt=\"\" width=\"24\" height=\"24\" src=\"https://sea1.discourse-cdn.com/foundationdb/user_avatar/forums.foundationdb.org/lehu/48/995_2.png\" class=\"avatar\"> lehu:</div>\n<blockquote>\n<p>Restarting fdbserver gave me this error:</p>\n<pre><code class=\"lang-auto\">root@tls62-storage-01-76cd5f5b99-c9w22:~# fdbserver -C /var/lib/foundationdb/fdb.cluster -p 10.104.193.12:4500 -p 10.104.193.12:4501:tls\n\n    Error initializing networking with public address 10.104.193.12:4500 and listen address 10.104.193.12:4500 (Local address in use)\n\n    Try `fdbserver --help' for more information.\n</code></pre>\n</blockquote>\n</aside>\n<p>Is there any other process already using the 4500 port? Or did this happen to eventually clear itself up?</p>",
        "post_number": 2,
        "post_type": 1,
        "posts_count": 12,
        "updated_at": "2020-01-23T17:37:52.174Z",
        "reply_count": 1,
        "reply_to_post_number": null,
        "quote_count": 1,
        "incoming_link_count": 5,
        "reads": 50,
        "readers_count": 49,
        "score": 40.0,
        "yours": false,
        "topic_id": 1904,
        "topic_slug": "issues-with-v6-2-tls-cluster",
        "display_username": "A.J. Beamon",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": true,
        "staff": true,
        "user_id": 12,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/issues-with-v6-2-tls-cluster/1904/2",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6017,
        "name": "Leo Hu",
        "username": "lehu",
        "avatar_template": "/user_avatar/forums.foundationdb.org/lehu/{size}/995_2.png",
        "created_at": "2020-01-23T23:52:57.779Z",
        "cooked": "<p>Hi AJ,</p>\n<p>I checked the port 4500. I believe it\u2019s not in use.</p>\n<pre><code>root@tls62wt222-storage-01-7fdf658588-m8w5l:~# netstat -peanut\nActive Internet connections (servers and established)\nProto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name\ntcp        0      0 10.104.193.72:4501      0.0.0.0:*               LISTEN      105        2489893358  -               \nroot@tls62wt222-storage-01-7fdf658588-m8w5l:~# \n</code></pre>\n<p>Note: You may notice the IP above is different from my previous post. That\u2019s becuase I rebuilt a new Docker image with the netstat utility in order to see ports in use, and created a new fdb cluster (tls62wt222).</p>\n<p>From the fdb trace files, we suspect the following 2 issues:</p>\n<ul>\n<li>The \u201c4500:tls\u201d process was not able to be started.</li>\n<li>The \u201cmake_public.py -t\u201d cmd made \u201c4500:tls\u201d, but didn\u2019t make 4501 as tls.</li>\n</ul>\n<p>I\u2019d like upload the trace files for your reference, but it seems only image files can be uploaded to the forum.</p>\n<p>Thank you.</p>\n<p>Leo</p>",
        "post_number": 3,
        "post_type": 1,
        "posts_count": 12,
        "updated_at": "2020-01-23T23:52:57.779Z",
        "reply_count": 1,
        "reply_to_post_number": 2,
        "quote_count": 0,
        "incoming_link_count": 3,
        "reads": 48,
        "readers_count": 47,
        "score": 29.6,
        "yours": false,
        "topic_id": 1904,
        "topic_slug": "issues-with-v6-2-tls-cluster",
        "display_username": "Leo Hu",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 12,
          "username": "ajbeamon",
          "name": "A.J. Beamon",
          "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 643,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/issues-with-v6-2-tls-cluster/1904/3",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6047,
        "name": "Leo Hu",
        "username": "lehu",
        "avatar_template": "/user_avatar/forums.foundationdb.org/lehu/{size}/995_2.png",
        "created_at": "2020-01-27T20:00:35.137Z",
        "cooked": "<p>The documentation on TLS enabling is pretty short. The examples used seem to be for a cluster of a <strong>single node</strong> at  127.0.0.1.</p>\n<p>Some questions on how to apply the procedures to a <strong>multi-node</strong> cluster. On \u201cEnabling TLS in a new cluster\u201d section:</p>\n<ul>\n<li>Do I run \u201cmake_public.py -t\u201d only on the first node or on <strong>every</strong> node?</li>\n<li>When a node has multiple processes, how can I enable TLS on <strong>all</strong> processes? In my previous msg, it seems the server restart only affects processes listed in fdb.cluster as coords.</li>\n</ul>\n<p>Thanks.<br>\nLeo</p>",
        "post_number": 4,
        "post_type": 1,
        "posts_count": 12,
        "updated_at": "2020-01-27T20:00:35.137Z",
        "reply_count": 1,
        "reply_to_post_number": 3,
        "quote_count": 0,
        "incoming_link_count": 1,
        "reads": 41,
        "readers_count": 40,
        "score": 18.2,
        "yours": false,
        "topic_id": 1904,
        "topic_slug": "issues-with-v6-2-tls-cluster",
        "display_username": "Leo Hu",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 643,
          "username": "lehu",
          "name": "Leo Hu",
          "avatar_template": "/user_avatar/forums.foundationdb.org/lehu/{size}/995_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 643,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/issues-with-v6-2-tls-cluster/1904/4",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6049,
        "name": "Leo Hu",
        "username": "lehu",
        "avatar_template": "/user_avatar/forums.foundationdb.org/lehu/{size}/995_2.png",
        "created_at": "2020-01-27T20:06:13.046Z",
        "cooked": "<p><span class=\"mention\">@Apple</span>  Do you have a more detailed doc on TLS enabing?</p>\n<p><span class=\"mention\">@Community</span> Has any of you enabled a multi-node cluster of v6.2 successfully? I\u2019ll appreciate your sharing your experience.</p>\n<p>Leo</p>",
        "post_number": 5,
        "post_type": 1,
        "posts_count": 12,
        "updated_at": "2020-01-27T20:06:13.046Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 0,
        "reads": 39,
        "readers_count": 38,
        "score": 7.8,
        "yours": false,
        "topic_id": 1904,
        "topic_slug": "issues-with-v6-2-tls-cluster",
        "display_username": "Leo Hu",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 643,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/issues-with-v6-2-tls-cluster/1904/5",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6051,
        "name": "A.J. Beamon",
        "username": "ajbeamon",
        "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png",
        "created_at": "2020-01-27T20:16:23.049Z",
        "cooked": "<aside class=\"quote no-group\" data-username=\"lehu\" data-post=\"4\" data-topic=\"1904\">\n<div class=\"title\">\n<div class=\"quote-controls\"></div>\n<img loading=\"lazy\" alt=\"\" width=\"24\" height=\"24\" src=\"https://sea1.discourse-cdn.com/foundationdb/user_avatar/forums.foundationdb.org/lehu/48/995_2.png\" class=\"avatar\"> lehu:</div>\n<blockquote>\n<p>Do I run \u201cmake_public.py -t\u201d only on the first node or on <strong>every</strong> node?</p>\n</blockquote>\n</aside>\n<p>make_public.py is intended to be run on a single node cluster as you are preparing to build it up (see <a href=\"https://apple.github.io/foundationdb/building-cluster.html\" class=\"inline-onebox\">Building a Cluster \u2014 FoundationDB 7.1</a>). A roughly similar procedure (though I\u2019m not sure whether make_public can help) is the pre-6.1 steps:</p>\n<p><a href=\"https://apple.github.io/foundationdb/tls.html?highlight=make_public#converting-an-existing-cluster-to-use-tls-v6-1\" class=\"onebox\" target=\"_blank\" rel=\"noopener\">https://apple.github.io/foundationdb/tls.html?highlight=make_public#converting-an-existing-cluster-to-use-tls-v6-1</a></p>\n<aside class=\"quote no-group\" data-username=\"lehu\" data-post=\"4\" data-topic=\"1904\">\n<div class=\"title\">\n<div class=\"quote-controls\"></div>\n<img loading=\"lazy\" alt=\"\" width=\"24\" height=\"24\" src=\"https://sea1.discourse-cdn.com/foundationdb/user_avatar/forums.foundationdb.org/lehu/48/995_2.png\" class=\"avatar\"> lehu:</div>\n<blockquote>\n<p>When a node has multiple processes, how can I enable TLS on <strong>all</strong> processes? In my previous msg, it seems the server restart only affects processes listed in fdb.cluster as coords.</p>\n</blockquote>\n</aside>\n<p>Processes use TLS if the coordinators in the cluster file are configured to use TLS (note that you\u2019ll also need to configure any TLS related parameters for your key files, etc, on every process). Apparently in the mixed mode, you\u2019ll configure two addresses so that you can talk to TLS and non-TLS coordinators, but if you are only using TLS coordinators then you should only need one address.</p>\n<p>The documentation is a little confusing here, and I personally haven\u2019t done anything with converting clusters between non-TLS and TLS, so I\u2019m not sure if there are any hidden gotchas that I\u2019m unaware of.</p>",
        "post_number": 6,
        "post_type": 1,
        "posts_count": 12,
        "updated_at": "2020-01-27T20:16:23.049Z",
        "reply_count": 1,
        "reply_to_post_number": 4,
        "quote_count": 1,
        "incoming_link_count": 4,
        "reads": 38,
        "readers_count": 37,
        "score": 32.6,
        "yours": false,
        "topic_id": 1904,
        "topic_slug": "issues-with-v6-2-tls-cluster",
        "display_username": "A.J. Beamon",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "link_counts": [
          {
            "url": "https://apple.github.io/foundationdb/tls.html?highlight=make_public#converting-an-existing-cluster-to-use-tls-v6-1",
            "internal": false,
            "reflection": false,
            "title": "Transport Layer Security \u2014 FoundationDB 6.2",
            "clicks": 6
          },
          {
            "url": "https://apple.github.io/foundationdb/building-cluster.html",
            "internal": false,
            "reflection": false,
            "title": "Building a Cluster \u2014 FoundationDB 6.2",
            "clicks": 5
          }
        ],
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": true,
        "staff": true,
        "user_id": 12,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/issues-with-v6-2-tls-cluster/1904/6",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6056,
        "name": "Leo Hu",
        "username": "lehu",
        "avatar_template": "/user_avatar/forums.foundationdb.org/lehu/{size}/995_2.png",
        "created_at": "2020-01-27T22:24:39.726Z",
        "cooked": "<p>I have difficulties to configure the mixed mode. Simply switching one coord to tls will make the db unavailable.</p>\n<p>To speed up and to be able to check syslog, I moved to test with a single-node, multi-process cluster on a VM.  (Docker containers disable syslogs.)  Still have issues with this env.</p>\n<p>I started w one coord (\u201cfdbserver.4501:tls\u201d) in TLS and restarted fdb service, then the corresponding process for 450 would not start. Certificate-related files have been configured in foundationdb.conf. There was a error in syslog:<br>\n<code>ERROR: TLS state of public address auto:4501 does not match in coordinator list.</code></p>\n<p>The error is mentioned in a closed bug report for v6.1. Not sure why I still see it.<br>\n<aside class=\"onebox githubissue\">\n  <header class=\"source\">\n      <a href=\"https://github.com/apple/foundationdb/issues/1189\" target=\"_blank\" rel=\"nofollow noopener\">github.com/apple/foundationdb</a>\n  </header>\n  <article class=\"onebox-body\">\n    <div class=\"github-row\">\n  <div class=\"github-icon-container\" title=\"Issue\">\n\t  <svg width=\"60\" height=\"60\" class=\"github-icon\" viewbox=\"0 0 14 16\" aria-hidden=\"true\"><path d=\"M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 0 1 1.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z\"></path></svg>\n  </div>\n\n  <div class=\"github-info-container\">\n    <h4>\n      <a href=\"https://github.com/apple/foundationdb/issues/1189\" target=\"_blank\" rel=\"nofollow noopener\">fdbserver failing unnecessarily due to \"public address *** not found in coordinator list\"</a>\n    </h4>\n\n    <div class=\"github-info\">\n      <div class=\"date\">\n        opened <span class=\"discourse-local-date\" data-format=\"ll\" data-date=\"2019-02-26\" data-time=\"01:52:17\" data-timezone=\"UTC\">01:52AM - 26 Feb 19 UTC</span>\n      </div>\n\n        <div class=\"date\">\n          closed <span class=\"discourse-local-date\" data-format=\"ll\" data-date=\"2019-02-27\" data-time=\"19:24:56\" data-timezone=\"UTC\">07:24PM - 27 Feb 19 UTC</span>\n        </div>\n\n      <div class=\"user\">\n        <a href=\"https://github.com/tclinken\" target=\"_blank\" rel=\"nofollow noopener\">\n          <img alt=\"tclinken\" src=\"https://global.discourse-cdn.com/foundationdb/original/1X/5f52f5d9db07a12511cfa6514ab796d8fddee85a.jpeg\" class=\"onebox-avatar-inline\" width=\"20\" height=\"20\">\n          tclinken\n        </a>\n      </div>\n    </div>\n  </div>\n</div>\n\n<div class=\"github-row\">\n  <p class=\"github-content\">fdbserver is now only allowed to run with a public address that is in the coordinator list (unless the cluster uses...</p>\n</div>\n\n<div class=\"labels\">\n    <span style=\"display:inline-block;margin-top:2px;background-color: #B8B8B8;padding: 2px;border-radius: 4px;color: #fff;margin-left: 3px;\">bug</span>\n</div>\n\n  </article>\n  <div class=\"onebox-metadata\">\n    \n    \n  </div>\n  <div style=\"clear: both\"></div>\n</aside>\n</p>\n<p>If I revert all coords to non-TLS, then the coords are reachable, but the db is still unavailable.</p>\n<pre><code>fdb&gt; status details \nUsing cluster file `/etc/foundationdb/fdb.cluster'.\n\nThe coordinator(s) have no record of this database. Either the coordinator\naddresses are incorrect, the coordination state on those machines is missing, or\nno database has been created.\n  10.169.165.52:4501  (reachable)\n  10.169.165.52:4502  (reachable)\n  10.169.165.52:4503  (reachable)\n\nUnable to locate the data distributor worker.\nUnable to locate the ratekeeper worker.\n</code></pre>\n<p>I had started a total of 10 fdb processes. Why are Data Distributor and Ratekeeper workers not available?</p>\n<p>Versions I am using: FDB v6.2.11 on Ubuntu 18.04.</p>\n<p>Thanks.<br>\nLeo</p>",
        "post_number": 7,
        "post_type": 1,
        "posts_count": 12,
        "updated_at": "2020-01-27T22:24:39.726Z",
        "reply_count": 2,
        "reply_to_post_number": 6,
        "quote_count": 0,
        "incoming_link_count": 3,
        "reads": 41,
        "readers_count": 40,
        "score": 33.2,
        "yours": false,
        "topic_id": 1904,
        "topic_slug": "issues-with-v6-2-tls-cluster",
        "display_username": "Leo Hu",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "link_counts": [
          {
            "url": "https://github.com/apple/foundationdb/issues/1189",
            "internal": false,
            "reflection": false,
            "title": "fdbserver failing unnecessarily due to \"public address *** not found in coordinator list\" \u00b7 Issue #1189 \u00b7 apple/foundationdb \u00b7 GitHub",
            "clicks": 4
          },
          {
            "url": "https://github.com/tclinken",
            "internal": false,
            "reflection": false,
            "title": "tclinken (Trevor Clinkenbeard) \u00b7 GitHub",
            "clicks": 0
          }
        ],
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 12,
          "username": "ajbeamon",
          "name": "A.J. Beamon",
          "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 643,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/issues-with-v6-2-tls-cluster/1904/7",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6057,
        "name": "Leo Hu",
        "username": "lehu",
        "avatar_template": "/user_avatar/forums.foundationdb.org/lehu/{size}/995_2.png",
        "created_at": "2020-01-27T22:35:57.903Z",
        "cooked": "<p>The current fdb relies upon the coordinators for TLS settings, instead of having an independent flag or flags for TLS. I don\u2019t quite understand the design rationals. Can you please explain them and give more details on how the current mechanism work? Thank you.</p>\n<p>Leo</p>",
        "post_number": 8,
        "post_type": 1,
        "posts_count": 12,
        "updated_at": "2020-01-27T22:35:57.903Z",
        "reply_count": 0,
        "reply_to_post_number": 7,
        "quote_count": 0,
        "incoming_link_count": 3,
        "reads": 42,
        "readers_count": 41,
        "score": 23.4,
        "yours": false,
        "topic_id": 1904,
        "topic_slug": "issues-with-v6-2-tls-cluster",
        "display_username": "Leo Hu",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 643,
          "username": "lehu",
          "name": "Leo Hu",
          "avatar_template": "/user_avatar/forums.foundationdb.org/lehu/{size}/995_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 643,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/issues-with-v6-2-tls-cluster/1904/8",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6058,
        "name": "A.J. Beamon",
        "username": "ajbeamon",
        "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png",
        "created_at": "2020-01-27T23:21:45.848Z",
        "cooked": "<aside class=\"quote no-group\" data-username=\"lehu\" data-post=\"7\" data-topic=\"1904\">\n<div class=\"title\">\n<div class=\"quote-controls\"></div>\n<img loading=\"lazy\" alt=\"\" width=\"24\" height=\"24\" src=\"https://sea1.discourse-cdn.com/foundationdb/user_avatar/forums.foundationdb.org/lehu/48/995_2.png\" class=\"avatar\"> lehu:</div>\n<blockquote>\n<p>ERROR: TLS state of public address auto:4501 does not match in coordinator list.</p>\n</blockquote>\n</aside>\n<p>This isn\u2019t clear to me from the documentation, but it appears you\u2019ll need to specify your public address in a format that is consistent with the TLS state of the process in the coordinators list. In other words, if you have a process <code>127.0.0.1:4500:tls</code> in your cluster file, that process needs to have the public address <code>127.0.0.1:4500:tls</code>. If you don\u2019t include <code>:tls</code> in the process\u2019s public address, you\u2019ll get this error.</p>\n<p>It\u2019s possible you\u2019ll need to update all of your processes to have a <code>:tls</code> public address (possibly in addition to a non-TLS one).</p>\n<aside class=\"quote no-group\" data-username=\"lehu\" data-post=\"7\" data-topic=\"1904\">\n<div class=\"title\">\n<div class=\"quote-controls\"></div>\n<img loading=\"lazy\" alt=\"\" width=\"24\" height=\"24\" src=\"https://sea1.discourse-cdn.com/foundationdb/user_avatar/forums.foundationdb.org/lehu/48/995_2.png\" class=\"avatar\"> lehu:</div>\n<blockquote>\n<p>If I revert all coords to non-TLS, then the coords are reachable, but the db is still unavailable.</p>\n<pre><code class=\"lang-auto\">fdb&gt; status details \nUsing cluster file `/etc/foundationdb/fdb.cluster'.\n\nThe coordinator(s) have no record of this database. Either the coordinator\naddresses are incorrect, the coordination state on those machines is missing, or\nno database has been created.\n  10.169.165.52:4501  (reachable)\n  10.169.165.52:4502  (reachable)\n  10.169.165.52:4503  (reachable)\n\nUnable to locate the data distributor worker.\nUnable to locate the ratekeeper worker.\n</code></pre>\n</blockquote>\n</aside>\n<p>I\u2019m not sure the history of what\u2019s been done to this database, but at this point there seems to be no data (at least with respect to the coordinators\u2019 state). Hopefully this is a case where you never had data, in which case you can setup the database using <code>configure new &lt;storage engine&gt; &lt;replication mode&gt;</code>, but if you had data and lost it we\u2019d have to try to figure out what happened. For example, if you\u2019ve been moving around coordinators without using <code>fdbcli</code> or manually manipulating files, it\u2019s possible the cluster is no longer aware of the data that\u2019s there.</p>",
        "post_number": 9,
        "post_type": 1,
        "posts_count": 12,
        "updated_at": "2020-01-27T23:21:45.848Z",
        "reply_count": 1,
        "reply_to_post_number": 7,
        "quote_count": 1,
        "incoming_link_count": 2,
        "reads": 46,
        "readers_count": 45,
        "score": 24.2,
        "yours": false,
        "topic_id": 1904,
        "topic_slug": "issues-with-v6-2-tls-cluster",
        "display_username": "A.J. Beamon",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": true,
        "staff": true,
        "user_id": 12,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/issues-with-v6-2-tls-cluster/1904/9",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6061,
        "name": "Leo Hu",
        "username": "lehu",
        "avatar_template": "/user_avatar/forums.foundationdb.org/lehu/{size}/995_2.png",
        "created_at": "2020-01-28T06:33:38.461Z",
        "cooked": "<p>I restarted everything from scratch (uninstalled and reinstalled fdb software), took your advice to keep coord spec and the process\u2019 public address consistent. I\u2019m able to go a step further.</p>\n<p>I started w 1 process at 4500. The db was available. Then ran  <code>sudo /usr/lib/foundationdb/make_public.py -t</code>. Afterwards, I needed to restart the 4500 process w tls public address as follows:</p>\n<p><code>sudo kill 6580</code>. # kill the process first</p>\n<p>sudo -u foundationdb  /usr/sbin/fdbserver -C /etc/foundationdb/fdb.cluster --datadir /var/lib/foundationdb/data/4500 --listen_address public --logdir /var/log/foundationdb --public_address auto:4500:tls  --tls_ca_file /etc/foundationdb/ca-cert.cert --tls_certificate_file /etc/foundationdb/cert.cert --tls_key_file /etc/foundationdb/key-file.key &amp;</p>\n<p>The db was OK.</p>\n<p>I added 2 more processes 4501 and 4502 to foundationdb.conf. The db was OK with 1 TLS process and 2 non-TLS processes:</p>\n<pre><code>Process performance details:\n      10.169.165.52:4501     (  2% cpu;  2% machine; 0.000 Gbps;  0% disk IO; 0.4 GB / 2.8 GB RAM  )\n      10.169.165.52:4502     (  3% cpu;  2% machine; 0.000 Gbps;  0% disk IO; 0.4 GB / 2.8 GB RAM  )\n      10.169.165.52:4500:tls (  3% cpu;  2% machine; 0.000 Gbps;  0% disk IO; 0.4 GB / 2.8 GB RAM  )\nCoordination servers:\n      10.169.165.52:4500:tls  (reachable)\n</code></pre>\n<p>Then I added TLS to 4501 in fdb.cluster, killed the old 4501 process, and restarted it w TLS:</p>\n<p><code>sudo -u foundationdb  /usr/sbin/fdbserver -C /etc/foundationdb/fdb.cluster -d /var/lib/foundationdb/data/4501 -L /var/log/foundationdb -p auto:4501:tls  --tls_ca_file /etc/foundationdb/ca-cert.cert --tls_certificate_file /etc/foundationdb/cert.cert --tls_key_file /etc/foundationdb/key-file.key &amp; </code></p>\n<p>It took a couple of mins for the db to stabilize. The db was available, but I got this <code>status details</code> output with a warning/error for 4500:</p>\n<pre><code>Process performance details:\n  10.169.165.52:4502     (  2% cpu;  3% machine; 0.000 Gbps;  0% disk IO; 0.4 GB / 2.8 GB RAM  )\n  10.169.165.52:4500:tls (  2% cpu;  3% machine; 0.000 Gbps;  0% disk IO; 0.4 GB / 2.8 GB RAM  )\n    Cluster file contents do not match current cluster connection string. Verify the cluster file and its parent directory are writable and that the cluster file has not been overwritten externally.\n  10.169.165.52:4501:tls (  3% cpu;  3% machine; 0.000 Gbps;  0% disk IO; 0.4 GB / 2.8 GB RAM  )\nCoordination servers:\n  10.169.165.52:4500:tls  (reachable)\n  10.169.165.52:4501:tls  (reachable)\n</code></pre>\n<p>What could have caused the warning/error \u201cCluster file contents do not match current cluster connection string\u201d?</p>\n<p>Thanks<br>\nLeo</p>",
        "post_number": 10,
        "post_type": 1,
        "posts_count": 12,
        "updated_at": "2020-01-28T06:33:38.461Z",
        "reply_count": 1,
        "reply_to_post_number": 9,
        "quote_count": 0,
        "incoming_link_count": 2,
        "reads": 40,
        "readers_count": 39,
        "score": 23.0,
        "yours": false,
        "topic_id": 1904,
        "topic_slug": "issues-with-v6-2-tls-cluster",
        "display_username": "Leo Hu",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 12,
          "username": "ajbeamon",
          "name": "A.J. Beamon",
          "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 643,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/issues-with-v6-2-tls-cluster/1904/10",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6062,
        "name": "Leo Hu",
        "username": "lehu",
        "avatar_template": "/user_avatar/forums.foundationdb.org/lehu/{size}/995_2.png",
        "created_at": "2020-01-28T06:44:13.123Z",
        "cooked": "<p>After I enabled 4502 for TLS (done similarly as for 4501), I got this</p>\n<pre><code>fdb&gt; status\nUsing cluster file `/etc/foundationdb/fdb.cluster'.\nLocking coordination state. Verify that a majority of coordination server\nprocesses are active.\n  10.169.165.52:4500:tls  (reachable)\n  10.169.165.52:4501:tls  (reachable)\n  10.169.165.52:4502:tls  (reachable)\n\nUnable to locate the data distributor worker.\nUnable to locate the ratekeeper worker.\n\nfdb&gt; coordinators \nCluster description: C0klmsUk\nCluster coordinators (3): 10.169.165.52:4500:tls,10.169.165.52:4501:tls,10.169.165.52:4502:tls</code></pre>",
        "post_number": 11,
        "post_type": 1,
        "posts_count": 12,
        "updated_at": "2020-01-28T06:44:13.123Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 1,
        "reads": 40,
        "readers_count": 39,
        "score": 13.0,
        "yours": false,
        "topic_id": 1904,
        "topic_slug": "issues-with-v6-2-tls-cluster",
        "display_username": "Leo Hu",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 643,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/issues-with-v6-2-tls-cluster/1904/11",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6069,
        "name": "A.J. Beamon",
        "username": "ajbeamon",
        "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png",
        "created_at": "2020-01-28T16:35:52.821Z",
        "cooked": "<aside class=\"quote no-group\" data-username=\"lehu\" data-post=\"10\" data-topic=\"1904\">\n<div class=\"title\">\n<div class=\"quote-controls\"></div>\n<img loading=\"lazy\" alt=\"\" width=\"24\" height=\"24\" src=\"https://sea1.discourse-cdn.com/foundationdb/user_avatar/forums.foundationdb.org/lehu/48/995_2.png\" class=\"avatar\"> lehu:</div>\n<blockquote>\n<p>What could have caused the warning/error \u201cCluster file contents do not match current cluster connection string\u201d?</p>\n</blockquote>\n</aside>\n<p>The error message has a few suggestions for this \u2013 namely that the permissions of the file or its folder are insufficient or that the file may have been modified externally. Have you ruled those out? In particular, if you are manually editing your cluster file, then you\u2019ll probably need to do so for every process in your cluster and then restart all of the processes.</p>\n<aside class=\"quote no-group\" data-username=\"lehu\" data-post=\"10\" data-topic=\"1904\">\n<div class=\"title\">\n<div class=\"quote-controls\"></div>\n<img loading=\"lazy\" alt=\"\" width=\"24\" height=\"24\" src=\"https://sea1.discourse-cdn.com/foundationdb/user_avatar/forums.foundationdb.org/lehu/48/995_2.png\" class=\"avatar\"> lehu:</div>\n<blockquote>\n<p>I added 2 more processes 4501 and 4502 to foundationdb.conf. The db was OK with 1 TLS process and 2 non-TLS processes:</p>\n</blockquote>\n</aside>\n<p>If you are going the route of converting your cluster to TLS when it is a single process, then my recommendation would be to add only TLS processes to it afterward. Although it should be possible to convert the cluster to mixed mode and back again, I don\u2019t think it\u2019s necessary that non-TLS processes be added.</p>",
        "post_number": 12,
        "post_type": 1,
        "posts_count": 12,
        "updated_at": "2020-01-28T16:35:52.821Z",
        "reply_count": 0,
        "reply_to_post_number": 10,
        "quote_count": 1,
        "incoming_link_count": 3,
        "reads": 41,
        "readers_count": 40,
        "score": 23.2,
        "yours": false,
        "topic_id": 1904,
        "topic_slug": "issues-with-v6-2-tls-cluster",
        "display_username": "A.J. Beamon",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": true,
        "staff": true,
        "user_id": 12,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/issues-with-v6-2-tls-cluster/1904/12",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      }
    ],
    "stream": [
      6010,
      6011,
      6017,
      6047,
      6049,
      6051,
      6056,
      6057,
      6058,
      6061,
      6062,
      6069
    ]
  },
  "timeline_lookup": [
    [
      1,
      2098
    ],
    [
      4,
      2094
    ],
    [
      12,
      2093
    ]
  ],
  "suggested_topics": [],
  "tags": [],
  "tags_descriptions": {},
  "fancy_title": "Issues with V6.2 TLS Cluster",
  "id": 1904,
  "title": "Issues with V6.2 TLS Cluster",
  "posts_count": 12,
  "created_at": "2020-01-23T17:31:13.342Z",
  "views": 1620,
  "reply_count": 8,
  "like_count": 0,
  "last_posted_at": "2020-01-28T16:35:52.821Z",
  "visible": true,
  "closed": false,
  "archived": false,
  "has_summary": false,
  "archetype": "regular",
  "slug": "issues-with-v6-2-tls-cluster",
  "category_id": 7,
  "word_count": 2538,
  "deleted_at": null,
  "user_id": 643,
  "featured_link": null,
  "pinned_globally": false,
  "pinned_at": null,
  "pinned_until": null,
  "image_url": null,
  "slow_mode_seconds": 0,
  "draft": null,
  "draft_key": "topic_1904",
  "draft_sequence": null,
  "unpinned": null,
  "pinned": false,
  "current_post_number": 1,
  "highest_post_number": 12,
  "deleted_by": null,
  "actions_summary": [
    {
      "id": 4,
      "count": 0,
      "hidden": false,
      "can_act": false
    },
    {
      "id": 8,
      "count": 0,
      "hidden": false,
      "can_act": false
    },
    {
      "id": 10,
      "count": 0,
      "hidden": false,
      "can_act": false
    },
    {
      "id": 7,
      "count": 0,
      "hidden": false,
      "can_act": false
    }
  ],
  "chunk_size": 20,
  "bookmarked": false,
  "topic_timer": null,
  "message_bus_last_id": 0,
  "participant_count": 2,
  "show_read_indicator": false,
  "thumbnails": null,
  "slow_mode_enabled_until": null,
  "tags_disable_ads": false,
  "related_topics": [
    {
      "fancy_title": "Enabling TLS on first install for single node setup",
      "id": 2111,
      "title": "Enabling TLS on first install for single node setup",
      "slug": "enabling-tls-on-first-install-for-single-node-setup",
      "posts_count": 3,
      "reply_count": 0,
      "highest_post_number": 3,
      "image_url": null,
      "created_at": "2020-05-09T09:32:49.925Z",
      "last_posted_at": "2021-06-30T10:51:48.211Z",
      "bumped": true,
      "bumped_at": "2021-06-30T10:51:48.211Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 4,
      "views": 1232,
      "category_id": 17,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": "latest",
          "description": "Original Poster, Most Recent Poster",
          "user": {
            "id": 476,
            "username": "dch",
            "name": "Dave Cottlehuber",
            "avatar_template": "/user_avatar/forums.foundationdb.org/dch/{size}/473_2.png",
            "trust_level": 2
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 863,
            "username": "Dretch",
            "name": "",
            "avatar_template": "/user_avatar/forums.foundationdb.org/dretch/{size}/1000_2.png",
            "trust_level": 1
          }
        }
      ]
    },
    {
      "fancy_title": "Foundationdb 6.3.9 with TLS &ndash; fdbcli status could not communicate with a quorum of coordination servers:",
      "id": 2704,
      "title": "Foundationdb 6.3.9 with TLS -- fdbcli status could not communicate with a quorum of coordination servers:",
      "slug": "foundationdb-6-3-9-with-tls-fdbcli-status-could-not-communicate-with-a-quorum-of-coordination-servers",
      "posts_count": 12,
      "reply_count": 4,
      "highest_post_number": 12,
      "image_url": null,
      "created_at": "2021-05-17T15:56:30.003Z",
      "last_posted_at": "2021-05-19T21:42:32.307Z",
      "bumped": true,
      "bumped_at": "2021-05-19T21:42:32.307Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 0,
      "views": 1613,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": null,
          "description": "Original Poster",
          "user": {
            "id": 865,
            "username": "manish-2014",
            "name": "Manish Sharan",
            "avatar_template": "/user_avatar/forums.foundationdb.org/manish-2014/{size}/1002_2.png",
            "trust_level": 1
          }
        },
        {
          "extras": "latest",
          "description": "Most Recent Poster",
          "user": {
            "id": 12,
            "username": "ajbeamon",
            "name": "A.J. Beamon",
            "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png",
            "admin": true,
            "trust_level": 4
          }
        }
      ]
    },
    {
      "fancy_title": "Set up fdb to use TLS failure with N2_ConnectError",
      "id": 3020,
      "title": "Set up fdb to use TLS failure with N2_ConnectError",
      "slug": "set-up-fdb-to-use-tls-failure-with-n2-connecterror",
      "posts_count": 9,
      "reply_count": 3,
      "highest_post_number": 9,
      "image_url": null,
      "created_at": "2021-11-19T08:38:17.530Z",
      "last_posted_at": "2021-11-23T00:53:27.886Z",
      "bumped": true,
      "bumped_at": "2021-11-23T05:48:39.795Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 1,
      "views": 1054,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": "latest",
          "description": "Original Poster, Most Recent Poster",
          "user": {
            "id": 1029,
            "username": "liuyan",
            "name": "",
            "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/l/839c29/{size}.png",
            "trust_level": 1
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 13,
            "username": "alexmiller",
            "name": "Alex Miller",
            "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
            "trust_level": 4
          }
        }
      ]
    },
    {
      "fancy_title": "(Solved) Correct setup of TLS for FoundationDB",
      "id": 1037,
      "title": "(Solved) Correct setup of TLS for FoundationDB",
      "slug": "solved-correct-setup-of-tls-for-foundationdb",
      "posts_count": 8,
      "reply_count": 3,
      "highest_post_number": 8,
      "image_url": null,
      "created_at": "2019-01-18T13:14:34.597Z",
      "last_posted_at": "2020-12-03T19:46:59.291Z",
      "bumped": true,
      "bumped_at": "2020-12-03T19:46:59.291Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 2,
      "views": 3516,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": null,
          "description": "Original Poster",
          "user": {
            "id": 483,
            "username": "Smerity",
            "name": "Stephen Merity",
            "avatar_template": "/user_avatar/forums.foundationdb.org/smerity/{size}/482_2.png",
            "trust_level": 1
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 120,
            "username": "josephg",
            "name": "Seph Gentle",
            "avatar_template": "/user_avatar/forums.foundationdb.org/josephg/{size}/84_2.png",
            "trust_level": 2
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 12,
            "username": "ajbeamon",
            "name": "A.J. Beamon",
            "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png",
            "admin": true,
            "trust_level": 4
          }
        },
        {
          "extras": "latest",
          "description": "Most Recent Poster",
          "user": {
            "id": 790,
            "username": "shubham4060",
            "name": "Shubham",
            "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/s/0ea827/{size}.png",
            "trust_level": 1
          }
        }
      ]
    },
    {
      "fancy_title": "Issue with TLS in foundationdb docker container",
      "id": 2504,
      "title": "Issue with TLS in foundationdb docker container",
      "slug": "issue-with-tls-in-foundationdb-docker-container",
      "posts_count": 5,
      "reply_count": 2,
      "highest_post_number": 5,
      "image_url": null,
      "created_at": "2021-01-05T02:45:20.081Z",
      "last_posted_at": "2021-01-05T06:25:52.461Z",
      "bumped": true,
      "bumped_at": "2021-01-05T06:25:52.461Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 1,
      "views": 614,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": "latest",
          "description": "Original Poster, Most Recent Poster",
          "user": {
            "id": 772,
            "username": "antonprabin",
            "name": "Prabin Poulose",
            "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/a/7cd45c/{size}.png",
            "trust_level": 1
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 13,
            "username": "alexmiller",
            "name": "Alex Miller",
            "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
            "trust_level": 4
          }
        }
      ]
    }
  ],
  "summarizable": false,
  "can_vote": false,
  "vote_count": 0,
  "user_voted": false,
  "discourse_zendesk_plugin_zendesk_id": null,
  "discourse_zendesk_plugin_zendesk_url": "https://your-url.zendesk.com/agent/tickets/",
  "details": {
    "can_edit": false,
    "notification_level": 1,
    "participants": [
      {
        "id": 643,
        "username": "lehu",
        "name": "Leo Hu",
        "avatar_template": "/user_avatar/forums.foundationdb.org/lehu/{size}/995_2.png",
        "post_count": 8,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "trust_level": 1
      },
      {
        "id": 12,
        "username": "ajbeamon",
        "name": "A.J. Beamon",
        "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png",
        "post_count": 4,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "admin": true,
        "trust_level": 4
      }
    ],
    "created_by": {
      "id": 643,
      "username": "lehu",
      "name": "Leo Hu",
      "avatar_template": "/user_avatar/forums.foundationdb.org/lehu/{size}/995_2.png"
    },
    "last_poster": {
      "id": 12,
      "username": "ajbeamon",
      "name": "A.J. Beamon",
      "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png"
    },
    "links": [
      {
        "url": "https://apple.github.io/foundationdb/tls.html",
        "title": "Transport Layer Security \u2014 FoundationDB 6.2",
        "internal": false,
        "attachment": false,
        "reflection": false,
        "clicks": 8,
        "user_id": 643,
        "domain": "apple.github.io",
        "root_domain": "apple.github.io"
      },
      {
        "url": "https://apple.github.io/foundationdb/tls.html?highlight=make_public#converting-an-existing-cluster-to-use-tls-v6-1",
        "title": "Transport Layer Security \u2014 FoundationDB 6.2",
        "internal": false,
        "attachment": false,
        "reflection": false,
        "clicks": 6,
        "user_id": 12,
        "domain": "apple.github.io",
        "root_domain": "apple.github.io"
      },
      {
        "url": "https://apple.github.io/foundationdb/building-cluster.html",
        "title": "Building a Cluster \u2014 FoundationDB 6.2",
        "internal": false,
        "attachment": false,
        "reflection": false,
        "clicks": 5,
        "user_id": 12,
        "domain": "apple.github.io",
        "root_domain": "apple.github.io"
      },
      {
        "url": "https://github.com/apple/foundationdb/issues/1189",
        "title": "fdbserver failing unnecessarily due to \"public address *** not found in coordinator list\" \u00b7 Issue #1189 \u00b7 apple/foundationdb \u00b7 GitHub",
        "internal": false,
        "attachment": false,
        "reflection": false,
        "clicks": 4,
        "user_id": 643,
        "domain": "github.com",
        "root_domain": "github.com"
      }
    ]
  },
  "bookmarks": []
}