{
  "post_stream": {
    "posts": [
      {
        "id": 14958,
        "name": "Matthieu Patou",
        "username": "mpatou_openai",
        "avatar_template": "/user_avatar/forums.foundationdb.org/mpatou_openai/{size}/1883_2.png",
        "created_at": "2025-05-31T01:52:41.447Z",
        "cooked": "<p>Hello there,<br>\nIn the series of tests that I have been conducting one of them is related to failover with a multi region fdb.</p>\n<p>Here is the configuration:</p>\n<pre><code class=\"lang-auto\">Configuration:\n  Redundancy mode        - double\n  Storage engine         - ssd-2\n  Log engine             - ssd-2\n  Encryption at-rest     - disabled\n  Coordinators           - 9\n  Desired Commit Proxies - 3\n  Desired GRV Proxies    - 5\n  Desired Resolvers      - 2\n  Desired Logs           - 3\n  Desired Remote Logs    - 3\n  Desired Log Routers    - 2\n  Usable Regions         - 2\n  Regions:\n    Remote -\n        Datacenter                    - trt0\n        Satellite datacenters         - trt4\n        Satellite Redundancy Mode     - one_satellite_double\n        Satellite Logs                - 2\n    Primary -\n        Datacenter                    - trt1\n        Satellite datacenters         - trt5\n        Satellite Redundancy Mode     - one_satellite_double\n        Satellite Logs                - 2\n\n</code></pre>\n<p>Is the region of the datacenter trt0 I deleted the operator and then all the pod related to FDB which correctly led to a failover but I noticed that there was no datamovement after the fail over which is a sign that something is not going well.<br>\nAnd when I connected to a pod and ran <code>fdbcli</code> I got</p>\n<pre><code class=\"lang-auto\">  Warning: the database may have data loss and availability loss. Please restart following tlog interfaces, otherwise storage servers may never be able to catch up.\n  Old log epoch: 416 begin: 1469148180768 end: 1469914254878, missing log interfaces(id,address): 5ca7231f5aa0c2b1, 13a9b489bdb7574a, d5bf8a8d39512900,\n</code></pre>\n<p>This somewhat came as a surprise as we are supposed to have multi region with a primary and satellite so in theory anything committed to the primary should also be committed to the satellite and copied over when there is a failover but somehow it seems not to be the case ?</p>\n<p>Is it a real issue ? also how do you map the id to pods or log server ?</p>",
        "post_number": 1,
        "post_type": 1,
        "posts_count": 10,
        "updated_at": "2025-05-31T01:52:41.447Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 10,
        "reads": 27,
        "readers_count": 26,
        "score": 25.4,
        "yours": false,
        "topic_id": 4921,
        "topic_slug": "dataloss-when-doing-failover-with-a-multi-region-cluster",
        "display_username": "Matthieu Patou",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 1484,
        "hidden": false,
        "trust_level": 2,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/dataloss-when-doing-failover-with-a-multi-region-cluster/4921/1",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null,
        "can_vote": false
      },
      {
        "id": 14975,
        "name": "Johannes Scheuermann",
        "username": "johscheuer",
        "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/j/f475e1/{size}.png",
        "created_at": "2025-06-05T07:40:22.245Z",
        "cooked": "<p>Maybe this is related to: <a href=\"https://forums.foundationdb.org/t/3dc2regions-simulating-primary-datacenter-failure/3329/\" class=\"inline-onebox\">3DC2regions--Simulating Primary Datacenter Failure</a></p>",
        "post_number": 2,
        "post_type": 1,
        "posts_count": 10,
        "updated_at": "2025-06-05T07:40:22.245Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 1,
        "reads": 22,
        "readers_count": 21,
        "score": 9.4,
        "yours": false,
        "topic_id": 4921,
        "topic_slug": "dataloss-when-doing-failover-with-a-multi-region-cluster",
        "display_username": "Johannes Scheuermann",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "link_counts": [
          {
            "url": "https://forums.foundationdb.org/t/3dc2regions-simulating-primary-datacenter-failure/3329",
            "internal": true,
            "reflection": false,
            "title": "3DC2regions--Simulating Primary Datacenter Failure",
            "clicks": 0
          }
        ],
        "read": true,
        "user_title": "",
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 849,
        "hidden": false,
        "trust_level": 2,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/dataloss-when-doing-failover-with-a-multi-region-cluster/4921/2",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 14981,
        "name": "Jingyu Zhou",
        "username": "jzhou",
        "avatar_template": "/user_avatar/forums.foundationdb.org/jzhou/{size}/445_2.png",
        "created_at": "2025-06-09T03:11:23.027Z",
        "cooked": "<p>AFAIK, this is not a real issue.</p>\n<p>When datacenter trt0 completed failed, FDB failed over to trt1. Because of complete failure of trt0, there won\u2019t be any data movement traffic cross regions.</p>\n<p>The <code>fdbcli</code> output is warning about old primary DC trt0, where data loss has happened (I bet these interfaces belong to trt0). However, because trt1 has replicas, so the database as a whole didn\u2019t have data loss. Because satellite trt4 is available, the new primary trt1 has all the mutation data before failover, thus can catch up without data loss. The warning is a bit confusing, but probably errs on the safe side.</p>\n<p>A tip on the operation:</p>\n<p>Usually when this happens, we will manually issue a region failover via fdbcli by updating DC priorities so that the primary will switch to be the original secondary, i.e., trt1 in your case.</p>\n<p>If such a manual failover is not issued, when the original primary trt0 (tlogs and storage servers) is brought back, FDB will try to use the original primary DC again. However, at this point of time, many storage servers are lagging behind, so Ratekeeper should throttle traffic until these storage servers are caught up. This behavior can validate that the database is already past the accepting_commit stage (write available) and the Ratekeeper\u2019s RkUpdate events (reason ID tells you why).</p>\n<p>Had the manual failover been issued, the behavior will be different: no throttling from Ratekeeper, and the database is available after brining the old primary DC back. Old primary will gradually catch up. When the old primary is sufficiently caught up, a manual failback can be issued and the old primary becomes primary again. If the failback is issued but the old primary has not caught up yet, the database will wait until DC lag is small enough and then switch regions (always available before failback).</p>\n<blockquote>\n<p>how do you map the id to pods or log server ?</p>\n</blockquote>\n<p>We usually search the ID string in the logs, e.g., <code>TLogMetrics</code> events for tlogs.</p>",
        "post_number": 3,
        "post_type": 1,
        "posts_count": 10,
        "updated_at": "2025-06-09T03:11:23.027Z",
        "reply_count": 1,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 4,
        "reads": 22,
        "readers_count": 21,
        "score": 44.4,
        "yours": false,
        "topic_id": 4921,
        "topic_slug": "dataloss-when-doing-failover-with-a-multi-region-cluster",
        "display_username": "Jingyu Zhou",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [
          {
            "id": 2,
            "count": 1
          }
        ],
        "moderator": true,
        "admin": true,
        "staff": true,
        "user_id": 454,
        "hidden": false,
        "trust_level": 2,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/dataloss-when-doing-failover-with-a-multi-region-cluster/4921/3",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 15182,
        "name": "Jillian Crossley",
        "username": "noctella",
        "avatar_template": "/user_avatar/forums.foundationdb.org/noctella/{size}/2015_2.png",
        "created_at": "2025-08-15T14:22:18.412Z",
        "cooked": "<p><a class=\"mention\" href=\"/u/jzhou\">@jzhou</a></p>\n<p>This is my current configuration:</p>\n<pre><code class=\"lang-auto\">\"regions\" : [\n                {\n                    \"datacenters\" : [\n                        {\n                            \"id\" : \"dc1\",\n                            \"priority\" : 1\n                        },\n                        {\n                            \"id\" : \"us-west-2\",\n                            \"priority\" : 1,\n                            \"satellite\" : 1\n                        }\n                    ],\n                    \"satellite_logs\" : 3,\n                    \"satellite_redundancy_mode\" : \"one_satellite_single\"\n                },\n                {\n                    \"datacenters\" : [\n                        {\n                            \"id\" : \"dc2\",\n                            \"priority\" : 0\n                        }\n                    ]\n                }\n            ],\n</code></pre>\n<p>I killed dc1, so now I have the following:</p>\n<pre><code class=\"lang-auto\">  Regions:\n    Remote -\n        Datacenter                    - dc1\n        Satellite datacenters         - us-west-2\n        Satellite Redundancy Mode     - one_satellite_single\n        Satellite Logs                - 3\n    Primary -\n        Datacenter                    - dc2\n</code></pre>\n<p>You mentioned about issuing a manual failover, but that doesn\u2019t work. I swapped the priorities of dc1/dc2 so that dc2 is primary.</p>\n<pre><code class=\"lang-auto\">sh-5.1$ fdbcli --exec \"configure  regions='[{\\\"datacenters\\\":[{\\\"id\\\":\\\"dc1\\\",\\\"priority\\\":0},{\\\"id\\\":\\\"us-west-2\\\",\\\"priority\\\":1,\\\"satellite\\\":1}],\\\"satellite_logs\\\":3,\\\"satellite_redundancy_mode\\\":\\\"one_satellite_single\\\"},{\\\"datacenters\\\":[{\\\"id\\\":\\\"dc2\\\",\\\"priority\\\":1}]}]'\"\nERROR: These changes would make the configuration invalid\n</code></pre>",
        "post_number": 4,
        "post_type": 1,
        "posts_count": 10,
        "updated_at": "2025-08-15T14:22:18.412Z",
        "reply_count": 1,
        "reply_to_post_number": 3,
        "quote_count": 0,
        "incoming_link_count": 1,
        "reads": 17,
        "readers_count": 16,
        "score": 13.4,
        "yours": false,
        "topic_id": 4921,
        "topic_slug": "dataloss-when-doing-failover-with-a-multi-region-cluster",
        "display_username": "Jillian Crossley",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 454,
          "username": "jzhou",
          "name": "Jingyu Zhou",
          "avatar_template": "/user_avatar/forums.foundationdb.org/jzhou/{size}/445_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 1594,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/dataloss-when-doing-failover-with-a-multi-region-cluster/4921/4",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 15184,
        "name": "Jingyu Zhou",
        "username": "jzhou",
        "avatar_template": "/user_avatar/forums.foundationdb.org/jzhou/{size}/445_2.png",
        "created_at": "2025-08-15T15:55:56.580Z",
        "cooked": "<p>The configuration is invalid because for the remote region, you don\u2019t have satellites configured, which is required for the region to become the primary.</p>",
        "post_number": 5,
        "post_type": 1,
        "posts_count": 10,
        "updated_at": "2025-08-15T15:55:56.580Z",
        "reply_count": 1,
        "reply_to_post_number": 4,
        "quote_count": 0,
        "incoming_link_count": 1,
        "reads": 17,
        "readers_count": 16,
        "score": 13.4,
        "yours": false,
        "topic_id": 4921,
        "topic_slug": "dataloss-when-doing-failover-with-a-multi-region-cluster",
        "display_username": "Jingyu Zhou",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 1594,
          "username": "noctella",
          "name": "Jillian Crossley",
          "avatar_template": "/user_avatar/forums.foundationdb.org/noctella/{size}/2015_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": true,
        "admin": true,
        "staff": true,
        "user_id": 454,
        "hidden": false,
        "trust_level": 2,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/dataloss-when-doing-failover-with-a-multi-region-cluster/4921/5",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 15186,
        "name": "Jillian Crossley",
        "username": "noctella",
        "avatar_template": "/user_avatar/forums.foundationdb.org/noctella/{size}/2015_2.png",
        "created_at": "2025-08-15T19:01:36.325Z",
        "cooked": "<p>I did also try swaping them so that dc2 has satellit:</p>\n<pre><code class=\"lang-auto\">sh-5.1$ fdbcli --exec \"configure double ssd-rocksdb-v1 usable_regions=2 logs=3 resolvers=1 log_routers=3 remote_logs=3 commit_proxies=2 grv_proxies=1 storage_migration_type=gradual perpetual_storage_wiggle=1 perpetual_storage_wiggle_locality=0 regions='[{\\\"datacenters\\\":[{\\\"id\\\":\\\"dc2\\\",\\\"priority\\\":1},{\\\"id\\\":\\\"us-west-2\\\",\\\"priority\\\":1,\\\"satellite\\\":1}],\\\"satellite_logs\\\":3,\\\"satellite_redundancy_mode\\\":\\\"one_satellite_single\\\"},{\\\"datacenters\\\":[{\\\"id\\\":\\\"dc1\\\",\\\"priority\\\":0}]}]'\"\nERROR: These changes would make the configuration invalid\n</code></pre>\n<p>Right now after the failover from dc1 to dc2 after I killed dc2 has left the cluster in a bad state:</p>\n<pre><code class=\"lang-auto\">  Warning: the database may have data loss and availability loss. Please restart following tlog interfaces, otherwise storage servers may never be able to catch up.\n  Old log epoch: 12 begin: 827334449 end: 1093552744, missing log interfaces(id,address): 61f46c21d2e4658d, 6c502d17604de6a5, 7e3b34298e52abf4,\n\n  Server time            - 08/15/25 18:58:38\n</code></pre>\n<p>I saw the message here: <a href=\"https://forums.foundationdb.org/t/dataloss-when-doing-failover-with-a-multi-region-cluster/4921\" class=\"inline-onebox\">Dataloss when doing failover with a multi region cluster?</a> that this might be benign.</p>\n<p>But when I also tried adding back dc1, now it\u2019s not recruiting any logs in dc1. A very similar thing happened when I tested killing dc2 with a healthy cluster \u2013 as soon as I added dc2 back, it was unable to recruit any logs there (and not enough storage servers either). The routers also moved to dc1 and did not move back to remote dc2.</p>\n<p>Seems like a fairly common failure testing scenario so not sure what I\u2019m doing wrong.</p>",
        "post_number": 6,
        "post_type": 1,
        "posts_count": 10,
        "updated_at": "2025-08-15T19:01:36.325Z",
        "reply_count": 1,
        "reply_to_post_number": 5,
        "quote_count": 0,
        "incoming_link_count": 0,
        "reads": 18,
        "readers_count": 17,
        "score": 8.6,
        "yours": false,
        "topic_id": 4921,
        "topic_slug": "dataloss-when-doing-failover-with-a-multi-region-cluster",
        "display_username": "Jillian Crossley",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 454,
          "username": "jzhou",
          "name": "Jingyu Zhou",
          "avatar_template": "/user_avatar/forums.foundationdb.org/jzhou/{size}/445_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 1594,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/dataloss-when-doing-failover-with-a-multi-region-cluster/4921/6",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 15195,
        "name": "Jillian Crossley",
        "username": "noctella",
        "avatar_template": "/user_avatar/forums.foundationdb.org/noctella/{size}/2015_2.png",
        "created_at": "2025-08-18T10:50:57.892Z",
        "cooked": "<p>To add a bit more detail here: I am trying to test multiregion failover in a setup managed by the fdb kubernetes operator.</p>\n<p>Primary: dc1, satellite us-west-2<br>\nRemote: dc2</p>\n<p>When I set skip=true in dc1 and deleted all of the dc1 pods, fdb failed over to dc2 fine, and when I set skip=false in dc1, everything came back fine and it automatically failed back to dc1. All good!</p>\n<p>However, I also wanted to test the case where dc1 is completely unrecoverable and we need to bring it back. For this test, I uninstalled the fdb deployment in dc1 (which removed the <code>foundationdbcluster</code> resource (that has all the pod/process class/pv information). It failed over to dc2 again as expected, but now I cannot figure out how to revive dc1.</p>\n<p>I cannot change the fdb configuration via cli \u2013 literally every attempt leads to <code>ERROR: These changes would make the configuration invalid</code>.</p>\n<p>I also tried re-installing the dc1 fdb deployment (with updated seed connection string), and although it can talk to the cluster, it cannot recover past the accepting_commits stage, and no tlogs are being recruited.</p>\n<p>What is the suggested way here to bring this cluster back? ty!</p>",
        "post_number": 7,
        "post_type": 1,
        "posts_count": 10,
        "updated_at": "2025-08-18T10:50:57.892Z",
        "reply_count": 1,
        "reply_to_post_number": 6,
        "quote_count": 0,
        "incoming_link_count": 0,
        "reads": 17,
        "readers_count": 16,
        "score": 8.4,
        "yours": false,
        "topic_id": 4921,
        "topic_slug": "dataloss-when-doing-failover-with-a-multi-region-cluster",
        "display_username": "Jillian Crossley",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 1594,
          "username": "noctella",
          "name": "Jillian Crossley",
          "avatar_template": "/user_avatar/forums.foundationdb.org/noctella/{size}/2015_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 1594,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/dataloss-when-doing-failover-with-a-multi-region-cluster/4921/7",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 15246,
        "name": "Jingyu Zhou",
        "username": "jzhou",
        "avatar_template": "/user_avatar/forums.foundationdb.org/jzhou/{size}/445_2.png",
        "created_at": "2025-08-22T22:13:40.628Z",
        "cooked": "<p>Not sure if fdb kubernetes operator can do the following and you might need manually do:</p>\n<ul>\n<li>After fail over to DC2, change usable_regions to 1, and then drop DC1 in the configuration. These configuration changes might need to be done in two steps.</li>\n<li>Bring back a set of processes in DC1.</li>\n<li>Add DC1 to the configuration, and then change usable_regions to 2.</li>\n</ul>\n<p>Note DC2 will also need satellites when there are two regions and DC2 is the primary.</p>",
        "post_number": 8,
        "post_type": 1,
        "posts_count": 10,
        "updated_at": "2025-08-22T22:14:04.829Z",
        "reply_count": 1,
        "reply_to_post_number": 7,
        "quote_count": 0,
        "incoming_link_count": 0,
        "reads": 12,
        "readers_count": 11,
        "score": 7.4,
        "yours": false,
        "topic_id": 4921,
        "topic_slug": "dataloss-when-doing-failover-with-a-multi-region-cluster",
        "display_username": "Jingyu Zhou",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 1594,
          "username": "noctella",
          "name": "Jillian Crossley",
          "avatar_template": "/user_avatar/forums.foundationdb.org/noctella/{size}/2015_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": true,
        "admin": true,
        "staff": true,
        "user_id": 454,
        "hidden": false,
        "trust_level": 2,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/dataloss-when-doing-failover-with-a-multi-region-cluster/4921/8",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 15286,
        "name": "Johannes Scheuermann",
        "username": "johscheuer",
        "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/j/f475e1/{size}.png",
        "created_at": "2025-09-01T16:43:51.109Z",
        "cooked": "<blockquote>\n<p>Not sure if fdb kubernetes operator can do the following and you might need manually do:</p>\n<ul>\n<li>After fail over to DC2, change usable_regions to 1, and then drop DC1 in the configuration. These configuration changes might need to be done in two steps.</li>\n<li>Bring back a set of processes in DC1.</li>\n<li>Add DC1 to the configuration, and then change usable_regions to 2.</li>\n</ul>\n<p>Note DC2 will also need satellites when there are two regions and DC2 is the primary.</p>\n</blockquote>\n<p>The operator can perform those steps, but they must be executed one by one.</p>\n<p>Depending on your setup and the failures that you are trying to test it might be worth to take a look at the <code>kubectl-fdb</code> plugin that has support for recovering a multi-region cluster in such cases: <a href=\"https://github.com/FoundationDB/fdb-kubernetes-operator/blob/main/kubectl-fdb/cmd/recover_multi_region_cluster.go\" class=\"inline-onebox\" rel=\"noopener nofollow ugc\">fdb-kubernetes-operator/kubectl-fdb/cmd/recover_multi_region_cluster.go at main \u00b7 FoundationDB/fdb-kubernetes-operator \u00b7 GitHub</a>. The intention of this command is a bit different since the idea is to make use of it if the cluster is in such a bad state, that you are not able to recover a majority of coordinators.</p>\n<p>Another side note for the multi-region setup with the operator: Since we don\u2019t have a global FoundationDBCluster spec (yet), you have to make sure to update all the configuration changes in all the different FoundationDBCluster specs that form the multi-region cluster (I hope that makes sense). Otherwise the different operator instances might have a different view on the desired state and they try to configure the cluster in different ways.</p>",
        "post_number": 9,
        "post_type": 1,
        "posts_count": 10,
        "updated_at": "2025-09-01T16:43:51.109Z",
        "reply_count": 0,
        "reply_to_post_number": 8,
        "quote_count": 0,
        "incoming_link_count": 0,
        "reads": 14,
        "readers_count": 13,
        "score": 2.8,
        "yours": false,
        "topic_id": 4921,
        "topic_slug": "dataloss-when-doing-failover-with-a-multi-region-cluster",
        "display_username": "Johannes Scheuermann",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "link_counts": [
          {
            "url": "https://github.com/FoundationDB/fdb-kubernetes-operator/blob/main/kubectl-fdb/cmd/recover_multi_region_cluster.go",
            "internal": false,
            "reflection": false,
            "title": "fdb-kubernetes-operator/kubectl-fdb/cmd/recover_multi_region_cluster.go at main \u00b7 FoundationDB/fdb-kubernetes-operator \u00b7 GitHub",
            "clicks": 1
          }
        ],
        "read": true,
        "user_title": "",
        "reply_to_user": {
          "id": 454,
          "username": "jzhou",
          "name": "Jingyu Zhou",
          "avatar_template": "/user_avatar/forums.foundationdb.org/jzhou/{size}/445_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 849,
        "hidden": false,
        "trust_level": 2,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/dataloss-when-doing-failover-with-a-multi-region-cluster/4921/9",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 15301,
        "name": "Jillian Crossley",
        "username": "noctella",
        "avatar_template": "/user_avatar/forums.foundationdb.org/noctella/{size}/2015_2.png",
        "created_at": "2025-09-05T12:15:12.586Z",
        "cooked": "<p>Thanks all. Wanted to follow up here in case anyone else is running into this issue.</p>\n<p>This is my exact setup:</p>\n<pre><code class=\"lang-auto\">dc: ${DC}\nusableRegions: 2\nredundancyMode: double\nstorageCount: 3\nlogCount: 3\ngrvProxyCount: 1\ncommitProxyCount: 2\nresolverCount: 1\nseedConnectionString: ${SEED_CONNECTION_STRING}\nregions:\n  - datacenters:\n      - id: ${PRIMARY}\n        priority: 1\n      - id: ${SATELLITE}\n        satellite: 1\n        priority: 1\n    satellite_logs: 3\n    satellite_redundancy_mode: one_satellite_single\n  - datacenters:\n      - id: ${REMOTE}\n        priority: 0\n</code></pre>\n<p>Scenario 1: PRIMARY is unavailable. This works well and is the common case of failure \u2013 we can fail back to PRIMARY automatically after it comes back online. I mocked this by killing all the fdb pods in PRIMARY and setting skip on operator so it doesn\u2019t revive them:</p>\n<pre><code class=\"lang-auto\">setSkipOnOperatorForDC \"$PRIMARY\" \"true\"\n\nkillPodsInDC \"$PRIMARY\"\n\n# The 'false' here means don't check data distribution state here. It will be stuck saying \"initializing\" until we fail back over.\nawaitFailover \"$REMOTE\" false\ncheckReconciliationForDC \"$REMOTE\"\n\nprint_green \"Automated failover to \"$REMOTE\" complete!\"\nsetSkipOnOperatorForDC \"$PRIMARY\" \"false\"\n\ncheckReconciliationForDC \"$PRIMARY\"\nawaitFailover \"$PRIMARY\"\n</code></pre>\n<p>Scenario 2: PRIMARY is unavailable and completely unrecoverable-- maybe kubernetes cluster went down and all data is lost. I mocked this by uninstalling the deployment in PRIMARY. dcs-final-failover.yaml contains the cluster in a failed-over state (ie REMOTE is now primary). Note that we need to manually force the failover into REMOTE \u2013 otherwise it complains that the configuration is invalid.</p>\n<pre><code class=\"lang-auto\">uninstallDC \"$PRIMARY\"\n\n# The 'false' here means don't check data distribution state here. It will be stuck saying \"initializing\" until we fail back over.\nawaitFailover \"$REMOTE\" false\n\nsetSkipOnOperatorForDC \"$SATELLITE\" \"true\"\nsetSkipOnOperatorForDC \"$REMOTE\" \"true\"\n\nprint_green \"Manually forcing failover to $REMOTE\"\nexecInPodInDC \"$REMOTE\" \"configure FORCE double ssd-rocksdb-v1 usable_regions=2 logs=3 resolvers=1 log_routers=3 remote_logs=-1 commit_proxies=2 grv_proxies=1 regions=[{\\\\\\\"datacenters\\\\\\\":[{\\\\\\\"id\\\\\\\":\\\\\\\"$PRIMARY\\\\\\\",\\\\\\\"priority\\\\\\\":-1},{\\\\\\\"id\\\\\\\":\\\\\\\"$SATELLITE\\\\\\\",\\\\\\\"priority\\\\\\\":1,\\\\\\\"satellite\\\\\\\":1}],\\\\\\\"satellite_logs\\\\\\\":3,\\\\\\\"satellite_redundancy_mode\\\\\\\":\\\\\\\"one_satellite_single\\\\\\\"},{\\\\\\\"datacenters\\\\\\\":[{\\\\\\\"id\\\\\\\":\\\\\\\"$REMOTE\\\\\\\",\\\\\\\"priority\\\\\\\":1}]}] storage_migration_type=gradual perpetual_storage_wiggle=1 perpetual_storage_wiggle_locality=0\"\n\nprint_green \"Setting usable regions to 1\"\nexecInPodInDC \"$REMOTE\" \"configure  FORCE double ssd-rocksdb-v1 usable_regions=1 logs=3 resolvers=1 log_routers=3 remote_logs=-1 commit_proxies=2 grv_proxies=1 regions=[{\\\\\\\"datacenters\\\\\\\":[{\\\\\\\"id\\\\\\\":\\\\\\\"$PRIMARY\\\\\\\",\\\\\\\"priority\\\\\\\":-1},{\\\\\\\"id\\\\\\\":\\\\\\\"$SATELLITE\\\\\\\",\\\\\\\"priority\\\\\\\":1,\\\\\\\"satellite\\\\\\\":1}],\\\\\\\"satellite_logs\\\\\\\":3,\\\\\\\"satellite_redundancy_mode\\\\\\\":\\\\\\\"one_satellite_single\\\\\\\"},{\\\\\\\"datacenters\\\\\\\":[{\\\\\\\"id\\\\\\\":\\\\\\\"$REMOTE\\\\\\\",\\\\\\\"priority\\\\\\\":1}]}] storage_migration_type=gradual perpetual_storage_wiggle=1 perpetual_storage_wiggle_locality=0\"\n\nawaitHealthyDataDistributionInDC \"$REMOTE\"\n\nprint_green \"Updating all DCs with the failed-over configuration and re-creating $PRIMARY.\"\nconnectionString=$(getConnectionStringForDC \"$REMOTE\")\n\ninstallInDC \"$REMOTE\" \"dcs-final-failover.yaml\" \"$connectionString\"\ninstallInDC \"$SATELLITE\" \"dcs-final-failover.yaml\" \"$connectionString\"\ninstallInDC \"$PRIMARY\" \"dcs-final-failover.yaml\" \"$connectionString\"\n\nsetSkipOnOperatorForDC \"$SATELLITE\" \"false\"\nsetSkipOnOperatorForDC \"$REMOTE\" \"false\"\n\ncheckReconciliationForDC \"$PRIMARY\" 30 # This recon takes longer due to the addition of new DCs\ncheckReconciliationForDC \"$SATELLITE\"\ncheckReconciliationForDC \"$REMOTE\"\n\nprint_green \"All datacenters reconciled successfully! Now manually failing back to $PRIMARY...\"\ninstallInDC \"$REMOTE\" \"dcs-final.yaml\" \"$connectionString\"\ninstallInDC \"$SATELLITE\" \"dcs-final.yaml\" \"$connectionString\"\ninstallInDC \"$PRIMARY\" \"dcs-final.yaml\" \"$connectionString\"\n\nawaitFailover \"$PRIMARY\"\n</code></pre>",
        "post_number": 10,
        "post_type": 1,
        "posts_count": 10,
        "updated_at": "2025-09-05T12:15:12.586Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 3,
        "reads": 12,
        "readers_count": 11,
        "score": 17.4,
        "yours": false,
        "topic_id": 4921,
        "topic_slug": "dataloss-when-doing-failover-with-a-multi-region-cluster",
        "display_username": "Jillian Crossley",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [
          {
            "id": 2,
            "count": 1
          }
        ],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 1594,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/dataloss-when-doing-failover-with-a-multi-region-cluster/4921/10",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      }
    ],
    "stream": [
      14958,
      14975,
      14981,
      15182,
      15184,
      15186,
      15195,
      15246,
      15286,
      15301
    ]
  },
  "timeline_lookup": [
    [
      1,
      144
    ],
    [
      2,
      139
    ],
    [
      3,
      135
    ],
    [
      4,
      67
    ],
    [
      7,
      64
    ],
    [
      8,
      60
    ],
    [
      9,
      50
    ],
    [
      10,
      46
    ]
  ],
  "suggested_topics": [],
  "tags": [],
  "tags_descriptions": {},
  "fancy_title": "Dataloss when doing failover with a multi region cluster?",
  "id": 4921,
  "title": "Dataloss when doing failover with a multi region cluster?",
  "posts_count": 10,
  "created_at": "2025-05-31T01:52:41.383Z",
  "views": 181,
  "reply_count": 6,
  "like_count": 2,
  "last_posted_at": "2025-09-05T12:15:12.586Z",
  "visible": true,
  "closed": false,
  "archived": false,
  "has_summary": false,
  "archetype": "regular",
  "slug": "dataloss-when-doing-failover-with-a-multi-region-cluster",
  "category_id": 17,
  "word_count": 2001,
  "deleted_at": null,
  "user_id": 1484,
  "featured_link": null,
  "pinned_globally": false,
  "pinned_at": null,
  "pinned_until": null,
  "image_url": null,
  "slow_mode_seconds": 0,
  "draft": null,
  "draft_key": "topic_4921",
  "draft_sequence": null,
  "unpinned": null,
  "pinned": false,
  "current_post_number": 1,
  "highest_post_number": 10,
  "deleted_by": null,
  "actions_summary": [
    {
      "id": 4,
      "count": 0,
      "hidden": false,
      "can_act": false
    },
    {
      "id": 8,
      "count": 0,
      "hidden": false,
      "can_act": false
    },
    {
      "id": 10,
      "count": 0,
      "hidden": false,
      "can_act": false
    },
    {
      "id": 7,
      "count": 0,
      "hidden": false,
      "can_act": false
    }
  ],
  "chunk_size": 20,
  "bookmarked": false,
  "topic_timer": null,
  "message_bus_last_id": 0,
  "participant_count": 4,
  "show_read_indicator": false,
  "thumbnails": null,
  "slow_mode_enabled_until": null,
  "tags_disable_ads": false,
  "related_topics": [
    {
      "fancy_title": "Simulating FDB data center failure",
      "id": 1790,
      "title": "Simulating FDB data center failure",
      "slug": "simulating-fdb-data-center-failure",
      "posts_count": 5,
      "reply_count": 2,
      "highest_post_number": 5,
      "image_url": null,
      "created_at": "2019-11-27T00:51:36.820Z",
      "last_posted_at": "2019-12-09T22:25:12.268Z",
      "bumped": true,
      "bumped_at": "2019-12-09T22:25:12.268Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [
        "performance"
      ],
      "tags_descriptions": {},
      "like_count": 0,
      "views": 977,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": null,
          "description": "Original Poster",
          "user": {
            "id": 550,
            "username": "ntrhieu89",
            "name": "Hieu Nguyen",
            "avatar_template": "/user_avatar/forums.foundationdb.org/ntrhieu89/{size}/587_2.png",
            "trust_level": 1
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 13,
            "username": "alexmiller",
            "name": "Alex Miller",
            "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
            "trust_level": 4
          }
        },
        {
          "extras": "latest",
          "description": "Most Recent Poster",
          "user": {
            "id": 12,
            "username": "ajbeamon",
            "name": "A.J. Beamon",
            "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png",
            "admin": true,
            "trust_level": 4
          }
        }
      ]
    },
    {
      "fancy_title": "3DC2regions&ndash;Simulating Primary Datacenter Failure",
      "id": 3329,
      "title": "3DC2regions--Simulating Primary Datacenter Failure",
      "slug": "3dc2regions-simulating-primary-datacenter-failure",
      "posts_count": 15,
      "reply_count": 11,
      "highest_post_number": 15,
      "image_url": "https://global.discourse-cdn.com/foundationdb/original/2X/a/a4c7fc1d6114672c9792f82339ddf436e6d9a7bd.png",
      "created_at": "2022-05-17T08:55:43.320Z",
      "last_posted_at": "2025-09-03T17:56:46.220Z",
      "bumped": true,
      "bumped_at": "2025-09-03T17:56:46.220Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [
        "bindings"
      ],
      "tags_descriptions": {},
      "like_count": 0,
      "views": 611,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": null,
          "description": "Original Poster",
          "user": {
            "id": 1095,
            "username": "Clindy",
            "name": "",
            "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/f04885/{size}.png",
            "trust_level": 1
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 1594,
            "username": "noctella",
            "name": "Jillian Crossley",
            "avatar_template": "/user_avatar/forums.foundationdb.org/noctella/{size}/2015_2.png",
            "trust_level": 1
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 1422,
            "username": "MarkSh1",
            "name": "Mark Sh1",
            "avatar_template": "/user_avatar/forums.foundationdb.org/marksh1/{size}/1789_2.png",
            "trust_level": 1
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 1484,
            "username": "mpatou_openai",
            "name": "Matthieu Patou",
            "avatar_template": "/user_avatar/forums.foundationdb.org/mpatou_openai/{size}/1883_2.png",
            "trust_level": 2
          }
        },
        {
          "extras": "latest",
          "description": "Most Recent Poster",
          "user": {
            "id": 1563,
            "username": "gridem-openai",
            "name": "Grigory Demchenko",
            "avatar_template": "/user_avatar/forums.foundationdb.org/gridem-openai/{size}/1981_2.png",
            "trust_level": 1
          }
        }
      ]
    },
    {
      "fancy_title": "Region failover: the criteria for auto failover and incremental/full refresh",
      "id": 3031,
      "title": "Region failover: the criteria for auto failover and incremental/full refresh",
      "slug": "region-failover-the-criteria-for-auto-failover-and-incremental-full-refresh",
      "posts_count": 1,
      "reply_count": 0,
      "highest_post_number": 1,
      "image_url": null,
      "created_at": "2021-11-23T20:58:48.381Z",
      "last_posted_at": "2021-11-23T20:58:48.444Z",
      "bumped": true,
      "bumped_at": "2021-11-23T20:58:48.444Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 0,
      "views": 453,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": "latest single",
          "description": "Original Poster, Most Recent Poster",
          "user": {
            "id": 643,
            "username": "lehu",
            "name": "Leo Hu",
            "avatar_template": "/user_avatar/forums.foundationdb.org/lehu/{size}/995_2.png",
            "trust_level": 1
          }
        }
      ]
    },
    {
      "fancy_title": "Working High Avalable Solutions with Two Datacenters",
      "id": 2380,
      "title": "Working High Avalable Solutions with Two Datacenters",
      "slug": "working-high-avalable-solutions-with-two-datacenters",
      "posts_count": 8,
      "reply_count": 5,
      "highest_post_number": 8,
      "image_url": null,
      "created_at": "2020-10-07T09:28:40.618Z",
      "last_posted_at": "2020-12-01T06:50:01.982Z",
      "bumped": true,
      "bumped_at": "2020-12-01T07:27:11.254Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 1,
      "views": 1171,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": "latest",
          "description": "Original Poster, Most Recent Poster",
          "user": {
            "id": 711,
            "username": "osamarin",
            "name": "Oleg Samarin",
            "avatar_template": "/user_avatar/forums.foundationdb.org/osamarin/{size}/905_2.png",
            "trust_level": 2
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 337,
            "username": "mengxu",
            "name": "Meng Xu",
            "avatar_template": "/user_avatar/forums.foundationdb.org/mengxu/{size}/893_2.png",
            "trust_level": 2
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 13,
            "username": "alexmiller",
            "name": "Alex Miller",
            "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
            "trust_level": 4
          }
        }
      ]
    },
    {
      "fancy_title": "Two region setup: fdb doesn&rsquo;t switch back to recovered primary idc",
      "id": 3102,
      "title": "Two region setup: fdb doesn't switch back to recovered primary idc",
      "slug": "two-region-setup-fdb-doesnt-switch-back-to-recovered-primary-idc",
      "posts_count": 5,
      "reply_count": 2,
      "highest_post_number": 5,
      "image_url": null,
      "created_at": "2022-01-06T09:20:23.617Z",
      "last_posted_at": "2022-01-25T09:00:26.631Z",
      "bumped": true,
      "bumped_at": "2022-01-25T09:00:26.631Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 1,
      "views": 507,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": "latest",
          "description": "Original Poster, Most Recent Poster",
          "user": {
            "id": 1037,
            "username": "leonliao",
            "name": "Leonliao",
            "avatar_template": "/user_avatar/forums.foundationdb.org/leonliao/{size}/1244_2.png",
            "trust_level": 2
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 13,
            "username": "alexmiller",
            "name": "Alex Miller",
            "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
            "trust_level": 4
          }
        }
      ]
    }
  ],
  "summarizable": false,
  "can_vote": false,
  "vote_count": 0,
  "user_voted": false,
  "discourse_zendesk_plugin_zendesk_id": null,
  "discourse_zendesk_plugin_zendesk_url": "https://your-url.zendesk.com/agent/tickets/",
  "details": {
    "can_edit": false,
    "notification_level": 1,
    "participants": [
      {
        "id": 1594,
        "username": "noctella",
        "name": "Jillian Crossley",
        "avatar_template": "/user_avatar/forums.foundationdb.org/noctella/{size}/2015_2.png",
        "post_count": 4,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "trust_level": 1
      },
      {
        "id": 454,
        "username": "jzhou",
        "name": "Jingyu Zhou",
        "avatar_template": "/user_avatar/forums.foundationdb.org/jzhou/{size}/445_2.png",
        "post_count": 3,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "admin": true,
        "moderator": true,
        "trust_level": 2
      },
      {
        "id": 849,
        "username": "johscheuer",
        "name": "Johannes Scheuermann",
        "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/j/f475e1/{size}.png",
        "post_count": 2,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "trust_level": 2
      },
      {
        "id": 1484,
        "username": "mpatou_openai",
        "name": "Matthieu Patou",
        "avatar_template": "/user_avatar/forums.foundationdb.org/mpatou_openai/{size}/1883_2.png",
        "post_count": 1,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "trust_level": 2
      }
    ],
    "created_by": {
      "id": 1484,
      "username": "mpatou_openai",
      "name": "Matthieu Patou",
      "avatar_template": "/user_avatar/forums.foundationdb.org/mpatou_openai/{size}/1883_2.png"
    },
    "last_poster": {
      "id": 1594,
      "username": "noctella",
      "name": "Jillian Crossley",
      "avatar_template": "/user_avatar/forums.foundationdb.org/noctella/{size}/2015_2.png"
    },
    "links": [
      {
        "url": "https://github.com/FoundationDB/fdb-kubernetes-operator/blob/main/kubectl-fdb/cmd/recover_multi_region_cluster.go",
        "title": "fdb-kubernetes-operator/kubectl-fdb/cmd/recover_multi_region_cluster.go at main \u00b7 FoundationDB/fdb-kubernetes-operator \u00b7 GitHub",
        "internal": false,
        "attachment": false,
        "reflection": false,
        "clicks": 1,
        "user_id": 849,
        "domain": "github.com",
        "root_domain": "github.com"
      }
    ]
  },
  "bookmarks": []
}